- agents/sflow.go
- analyzer/analyzer.go
- config/config.go
- etc/skydive.ini.default
- flow/flow.go
- mappings/mapper.go
- mappings/neutron.go
- ovs/ovsdb.go
- packet/packet.go
- skydive.go
- storage/elasticsearch/elasticsearch.go
- storage/storage.go
This patch introduces:
- mapping, first one is based on Openstack Neutron, retrieving TenantID
and VNI.
- analayzer, which is basically forwarding flow form agent to storage
using mapping to complete flow structure.
- config package, used currently in neutron mapping
- logging package, which is basically a helper
The neutron mapping is using a local in-memory cache that is updated in
an async way.
This patch fixes the concept of flow computing a unique flow id based on
headers.
> Introduce analyzer and mapping

- topology/netlink.go
- topology/netlink_test.go
https://github.com/vishvananda/netlink/pull/61
> Use original netlink library, PR merged

- README.md
- etc/skydive.ini.default
- skydive_analyzer/skydive_analyzer.go
- storage/elasticsearch/elasticsearch.go
"elasticsearch" key under "storage" section describe the connection to elasticsearch server.
[storage]
elasticsearch = 127.0.0.1:9200
> [storage] elasticsearch config

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/go-gremlin/gremlin/.gitignore
- Godeps/_workspace/src/github.com/go-gremlin/gremlin/LICENSE
- Godeps/_workspace/src/github.com/go-gremlin/gremlin/README.md
- Godeps/_workspace/src/github.com/go-gremlin/gremlin/connection.go
- Godeps/_workspace/src/github.com/go-gremlin/gremlin/glide.yaml
- Godeps/_workspace/src/github.com/go-gremlin/gremlin/request.go
- Godeps/_workspace/src/github.com/go-gremlin/gremlin/response-codes.go
- Godeps/_workspace/src/github.com/go-gremlin/gremlin/response.go
- Godeps/_workspace/src/github.com/satori/go.uuid/.travis.yml
- Godeps/_workspace/src/github.com/satori/go.uuid/LICENSE
- Godeps/_workspace/src/github.com/satori/go.uuid/README.md
- Godeps/_workspace/src/github.com/satori/go.uuid/uuid.go
- analyzer/server.go
- cmd/skydive_agent/skydive_agent.go
- etc/skydive.ini.default
- topology/graph/client.go
- topology/graph/graph.go
- topology/graph/gremlin.go
- topology/graph/gremlin/client.go
- topology/graph/server.go
- topology/probes/netlink.go
- topology/probes/ovsdb.go
This is a first implementation of a gremlin backend. There is a lot of
place for improvement leveraging the gremlin language.
> Introduce Gremlin graph backend

- topology/graph/graph.go
- topology/graph/graph_test.go
- topology/graph/memory.go
- topology/probes/netlink.go
- topology/probes/ovsdb.go
Some fixes around the topology graph
> Topology fixes

- topology/graph/memory.go
- topology/graph/memory_test.go
This patch initiate UTs for the memory backend
> Fix AddEdge in the memory backend, edge was added even with missing node

- analyzer/server.go
- cmd/skydive_agent/skydive_agent.go
- etc/skydive.ini.default
- topology/graph/server.go
Default pong timeout is set to 5 seconds
> Add config parameter in order to set the WebSocket pong timeout

- agent/agent.go
- cmd/skydive_agent/skydive_agent.go
- cmd/skydive_analyzer/skydive_analyzer.go
- config/config.go
- topology/server.go
Splitted out an agent can be instanciate and tested.
> Split out the agent main and the agent code aiming to instanciate agent

- .travis.yml
- config/config.go
- coverage.sh
- tests/tests.go
- tests/topology_test.go
This set of commit add functional tests and fix coverage reports
The PR https://github.com/redhat-cip/skydive/pull/41 needs to be merged before this could pass travis
> Add functional tests for topology

- README.md
Signed-off-by: Kyle Mestery <mestery@mestery.com>
> README.md: Line-wrap at 80 characters, spelling fixes, grammar fixes

- flow/table.go
- flow/table_test.go
SelectLayer(type, list) return the flows (unique) that match type layer
(Ethernet, IP, ...) with one of element in the list argurment.
> [flowtable] Introduce ft.SelectLayer()

- cmd/pcap2sflow-replay/pcap2sflow-replay.go
Fix -pktpersflow into -pktspersflow in pcap2sflow-replay command
> pcap2sflow-replay helper fix on -pktspersflow parameter

- storage/elasticsearch/elasticsearch.go
o Latest FlatFlow format that can be injected in ElasticSearch.
o Inject Flow in Bulk to ES server
> [storage][elasticsearch] New FlatFlow format

- README.md
- cmd/skydive_analyzer/skydive_analyzer.go
- storage/elasticsearch/elasticsearch.go
Fix elasticsearch storage which was broken, due to 
- bad usage of bulk indexer
- mapping non adapted after changing the flow format
> Fix ES storage

- Makefile
- alert/server.go
- scripts/ci/ansible/deploy.yml
- scripts/ci/ansible/roles/create_instances/defaults/main.yml
- scripts/ci/ansible/roles/create_instances/tasks/main.yml
- scripts/ci/ansible/roles/elasticsearch/tasks/main.yml
- scripts/ci/ansible/roles/jenkins_master/tasks/main.yml
- scripts/ci/ansible/roles/orientdb/defaults/main.yml
- scripts/ci/ansible/roles/orientdb/tasks/main.yml
- scripts/ci/cleanup.sh
- scripts/ci/jobs/jobs.yml
- scripts/ci/run-functional-tests.sh
- scripts/ci/run-go-fmt.sh
- scripts/ci/run-scale.sh
- scripts/ci/run-selenium-tests.sh
- scripts/ci/run-unit-tests.sh
- scripts/scale.sh
- sflow/agent.go
- tests/alert_test.go
- tests/api_test.go
- tests/flow_test.go
- tests/helper/helper.go
- tests/scale_test.go
- tests/tests.go
Change-Id: I2f22051d08285f76677af3fe00137c9edfcc7772
> ci: add ansible playbooks and jjb for the delivrance project

- scripts/ci/ansible/deploy.yml
- scripts/ci/ansible/roles/create_instances/tasks/main.yml
- Use private network for slave to master communications
- Install the ansicolor plugin
- Specify the Jenkins public IP when deploying
> CI improvements

- README.md
> Badges : Add goreportcard and coveralls community badges

- api/topology.go
- common/tls.go
- config/config.go
- http/auth.go
- http/basic.go
- http/client.go
- http/keystone.go
- http/server.go
- http/tls.go
- http/wsclient.go
- scripts/scale.sh
- statics/js/websocket.js
- tests/helper/helper.go
- tests/scale_test.go
Remove the old StopableListener as listener have a Close() method now and
StopableListener is not compatible with TLSListener (not exported).
> Full TLS support

- storage/elasticsearch/client.go
This avoid dead lock when having the chan full
> es: add error chan reader

- .gitattributes
Change-Id: I323189c5d43baa932f8c46a2ddc0c58fd6d52b46
> github : fix languages vendoring

- alert/server.go
- doc/content/api/alerts.md
- tests/alert_test.go
- tests/tests.go
fixes #281
Change-Id: Ic8d97c36225b19e8ee045827b65f232e23b4fc76
> Alert: Trigger alert when a successful evaluation changes

- common/types.go
- topology/graph/graph.go
currently we have set and get utils for tree(a.b.c.d) based key
adding the delete for the same.
> common: Delete util for tree based keys

- cmd/cmd.go
It is scaring to see a stack trace for
just a config file read error.
> cmd: do not panic on config read error

- .travis.yml
- config/config.go
- etc/skydive.yml.default
- logging/logging.go
- scripts/ci/run-devstack.sh
- vendor/vendor.json
> logging : add zap logger

- CONTRIBUTING.md
- Makefile
> contributing : making changes

- cmd/client/alert.go
- cmd/client/capture.go
- cmd/client/packet_injector.go
- cmd/client/pcap.go
- cmd/client/topology.go
it is scaring and unuseful to print
stack trace
> client: fix error handling

- contrib/docker/docker-compose.yml
Agent don't need anymore to access to etcd
> docker: no need to expose etcd anymore

- devstack/plugin.sh
For example with the following, elasticsearch will not be used:
SKYDIVE_FLOWS_STORAGE="none"
SKYDIVE_GRAPH_STORAGE="memory"
Also, one can choose keystone v2.0 instead of v3
> devstack: allow to disable storage

- statics/js/components/topology.js
logout throwing not a function exception for unwatch.
unwatch is defind now.
> ui: fix exception on logout

- statics/js/components/inject-form.js
> inject: add support for injecting payload with icmp packets (by length, to allow stress tests)

- contrib/python/api/websocket/client.py
To delete/update the nodes and edges in a given json.
According to issue #376
> client.py: add new arguments: "delete" and "update"

- http/wsmessage.go
- packet_injector/client.go
- packet_injector/inject_packet.go
- packet_injector/server.go
> packet-inject: fix injection outside of netns

- topology/graph/traversal/traversal.go
- topology/graph/traversal/traversal_parser.go
- topology/graph/traversal/traversal_scanner.go
- topology/graph/traversal/traversal_test.go
This allow to retrieves in and out
nodes of an edge.
ex: G.E().BothV()
> gremlin: add BothV step

- flow/flow.go
- flow/flow.proto
- flow/flow_test.go
- flow/storage/elasticsearch/elasticsearch.go
- flow/storage/orientdb/orientdb.go
- flow/table.go
- storage/elasticsearch/client.go
Calculated on first packet on each way like :
Latency = t1stBAPacket - t1stABPacket
> flow : add RTT

- .travis.yml
every coverage and tests should be done is
jenkins
> ci: remove coverage for travis since unstable

- flow/ondemand/server/server.go
> ondemand: fix race that may cause duplicate captures

- topology/probes/neutron.go
- vendor/vendor.json
> neutron : bump gophercloud version

- statics/js/components/graph-layout.js
- statics/js/components/topology.js
- topology/probes/netlink.go
This patch creates a group for parent interface
of vlan interfaces. This allows to expand collapse
all sub-interfaces.
Fixes: #402
> ui: add group for vlan interfaces

- statics/js/components/graph-layout.js
- topology/probes/neutron.go
> neutron: fix tap attached to host and remaining link

- scripts/ci/cleanup.sh
- statics/js/components/graph-layout.js
- topology/probes/neutron.go
This patch removes also the cache using a map instead
Closes: #148
> neutron: do not block anymore waiting for neutron

- statics/js/components/rule-detail.js
> ui: better handling of long openflow rules

- http/server.go
> http : shutdown connection gracefuly

- agent/probes.go
- config/config.go
- tests/topology_test.go
- topology/probes/docker.go
- topology/probes/netlink.go
- topology/probes/netns.go
This allows to add /var/run/docker/netns
> netns: allow to listen to events for multiple paths

- flow/enhancers/socket_info.go
- statics/js/components/capture-form.js
This enhancer has a huge impact on performances especially
with many new flows
> socketinfo: disable it by default and apply it only on tcp

- api/packet_injector.go
add mask to src and dst ips,
if not provided by user
> pi: add mask to src/dst ip

- etc/skydive.yml.default
- statics/js/app.js
- statics/js/components/topology.js
Initial Implementation
Find on graph selected via Gremlin Expression sub-graph and highlight it.
> Find: Highlight selected nodes

- statics/js/components/capture-form.js
The word "Optional" is misspelled in the UI.
> ui: Fix typo

- http/wsjson.go
- http/wsserver.go
> http: fix WSSPeaker typo

- common/types.go
- common/types_test.go
> flow: fix IPV4Range and add tests

- statics/js/components/graph-layout.js
> ui: reset link color when bandwidth below threshold

- tests/topology_test.go
- topology/probes/netlink.go
- vendor/vendor.json
this will display the route table info
in the metadata.
> probe: add route-table probe

- etc/skydive.yml.default
- http/server.go
- http/wsmessage_test.go
- http/wsserver_test.go
- statics/index.html
- statics/js/components/graph-layout.js
- statics/js/components/layout.js
Refactor the graph-layout in order
to allow to add/modify icons via
nodeImgMap javascript map.
Closes: #553
> ui: allow to add external JS/CSS

- etc/skydive.yml.default
- logging/logging.go
Also, remove invalid json backend from sample config.
> logging: add stdout backend

- statics/js/components/topology.js
1.close button while visible
2.added timeout to make visible
3.dispaly date and time in history mode
> ui: some improvements in left panel

- scripts/ci/cleanup.sh
This patch removed code duplication in `cleanup.sh` implementation - specifically using newly created functions `cleanup_items` and `snapshot_items` for eliminating most of the common code.
To that the patch introduced no depredations you can run: 
```
$ sudo scripts/ci/cleanup.sh init
... add netns, intf, bridge, docker, docker-images
$ sudo scripts/ci/cleanup.sh snapshot
$ sudo scripts/ci/cleanup.sh cleanup 2>&1 | tee run1.log
$ sudo scripts/ci/cleanup.sh snapshot
$ sodo scripts/ci/cleanup.sh cleanup 2>&1 | tee run2.log
```
> ci: reduced code duplication in cleanup.sh

- Makefile
this change is a small code refactor which should have a neutral effect on build functionality, and can be tested using:
```
$ make clean
$ make all
$ make static
$ ... etc ...
```
All these tests are automatically run by CI
> makefile: define macros for govendor invocations

- analyzer/probes.go
- statics/js/components/graph-layout.js
- statics/js/components/layout.js
- topology/probes/k8s/cache.go
- topology/probes/k8s/client.go
- topology/probes/k8s/k8s.go
- topology/probes/k8s/networkpolicy.go
- topology/probes/k8s/pod.go
to test look at a k8s cluster with pods and networkplocies
> K8s:  adding full metadata and some code improvements

- statics/css/graph-layout.css
- statics/js/components/graph-layout.js
check that links are assigned green, yellow, red and animation according to classification (already existing) to active, warning, alert.
> ui: animate and color links according to bw

- cmd/client/gremlin.go
- cmd/client/query.go
- cmd/client/shell.go
- tests/flow_test.go
- tests/tests.go
This aims to improve client performance.
> client: do not unmarshal/marshal reply from api

- topology/probes/opencontrail.go
- vendor/vendor.json
When collection.LoadCollection returns an error we should not call
Close() as col will refer to a nil pointer.
Rewrited the loop to make it more simple to read.
> opencontrail: close col only if it was loaded

- topology/probes/netlink.go
Use IfIndex instead of LinkIndex to be consistant and use int64
instead of int.
> netlink: fix routes not having IfIndex info and make use of IfIndex

- topology/probes/docker/docker.go
Test with both a docker probe and verify "Labels" field is in-tacked
> docker: use common.NormalizeValue() to set "Labels"

- common/debounce.go
- flow/ondemand/client/client.go
This aims to reduce the number of gremlin evaluation.
> capture: add debounce mechanism on graph events

- contrib/python/api/requirements.txt
- contrib/python/api/samples/inject-nodes1.py
- contrib/python/api/setup.cfg
- contrib/python/api/setup.py
- contrib/python/api/skydive/websocket/client.py
- contrib/python/api/skydive/wsshell.py
- contrib/python/api/tests/tests.py
Added modifications to the websocket client for better usability and debugging.
> Dragonflow changes

- etc/skydive.yml.default
- flow/ondemand/client/client.go
Invoke capture on preconfigured nodes automatically
from the beginning.
> capture: Invoke capture on preconfigured nodes

- flow/ondemand/client/client.go
- topology/graph/graph.go
- topology/probes/k8s/client.go
- topology/probes/k8s/container.go
- topology/probes/k8s/graph.go
- topology/probes/k8s/networkpolicy.go
- topology/probes/k8s/node.go
- topology/probes/k8s/pod.go
- topology/probes/k8s/probe.go
- topology/topology.go
Make improvements and fixes to the following links:
- pod --ownership--> node
- container --ownership--> pod
- container --association--> docker
- networkPolicy --association--> pod
> K8s: fixed issues related to links / ownership links

- contrib/kubernetes/skydive.yaml
you can test running:
```
cd contrib/kubernetes
kubectl delete -f skydive.yaml || true
kubectl create -f skydive.yaml
kubectl describe pods
```
> kubernetes: added livenessProbe to services in skydive.yaml

- contrib/python/api/setup.py
- contrib/python/api/skydive/websocket/client.py
Added cookie to self.cookie instead of self.cookies
> Fix a typo in the login method

- config/config.go
- etc/skydive.yml.default
- statics/js/components/layout.js
- tests/k8s/namespace.yaml
- tests/k8s_test.go
- topology/probes/k8s/container.go
- topology/probes/k8s/graph.go
- topology/probes/k8s/namespace.go
- topology/probes/k8s/networkpolicy.go
- topology/probes/k8s/node.go
- topology/probes/k8s/pod.go
- topology/probes/k8s/probe.go
- vendor/vendor.json
Added new k8s/namespace probe:
- creating a Node per each namespace
- creating an edge { "RelationType": "Association" } between namespaces to {pod,networkpolicy} objects
> K8s namespaces

- gremlin/query.go
- gremlin/query_test.go
- scripts/ci/run-k8s-tests.sh
- tests/helper/helper.go
- tests/k8s/networkpolicy.yaml
- tests/k8s_test.go
Fixed k8s tests (for checking creation of nodes). Please note that one has to run `scripts/ci/install-minikube.sh` on the target test VM prior to running the tests.
> K8s tests fix

- statics/css/skydive.css
- statics/js/components/graph-layout.js
- statics/js/components/preference.js
- statics/js/components/topology.js
preference can be download to file to share with others
and upload from file.
> ui: add file support for preference

- http/server.go
Added support in uploading from disk extra static assets which reside under a sub-folder such as:
```
x/y/z/my.css
```
> Ui extra assets recurse

- statics/js/components/flow-table.js
> ui: fix flow-table sort

- flow/ondemand/client/client.go
- tests/startup_capture_test.go
- tests/tests.go
Startup automatic capturing based on configuration
didnt work.
This patch is its fix.
> probe:fix: Fix startup automatic capturing

- statics/js/components/inject-form.js
fixing PI's source and destination node
highlight issue after analyzer reboot
> ui: fix highlight issue for PI nodes

- flow/ondemand/server/server.go
This allow to find node by capture name.
> capture: add capture name to node metadata

- gremlin/query.go
- gremlin/value.go
- tests/topology_test.go
If all tests run this change should be ok (as its' functionality natural)
> tests: create topology test queries using gremlin builder

- statics/js/components/graph-layout.js
We are attempting to calculate the latency between A to B by finding a flow
which has been seen in both points. Due to current limitions in Gremlin we
are not able to do so in a single query forcing us to:
- 1st find a flow which intersects with A (using a small queue)
- 2nd check if the discovered flow intersects with B
If the system is wieghted down with many unique flows running from A to C we
may fill the queue in phase 1 with flows from which we can't deduce latency
(between A to  B). Such as a case in which we had HTTP traffic (A -> B) and
many many flows of DNS traffic (A -> C).
The new implementation uses a very large queue for 1st phase but then reduces
it down to a limitted set of unique flows: comparing ANodeTID, BNodeTID,
Application. As 2nd step is expenssive we only pass on …
> ui: discover latency in very noisy environments

- scripts/simple.sh
Extended simple.sh (atop @safchain 's bridge related commit) so enable:
```
./simple.sh start                               # invocation using default subnets
./simple.sh start --delay                       # injection of netem delays
./simple.sh ping                                # ping: vm1-->vm2 and vm2-->vm1
```
> Scripts simple delay

- api/client/gremlin.go
- gremlin/query.go
- tests/api_test.go
- tests/cdd_test.go
- tests/docker_test.go
- tests/flow_ebpf_test.go
- tests/lxd_test.go
- tests/neutron_test.go
- tests/openflow_test.go
- tests/packet_injector_test.go
- tests/scale_test.go
- tests/selenium.go
- tests/selenium_test.go
> Tests all gremlin

- gremlin/traversal/flows.go
- gremlin/traversal/metrics.go
- gremlin/traversal/metrics_test.go
- gremlin/traversal/sockets.go
- gremlin/traversal/topology.go
- topology/graph/traversal/traversal.go
need to verify that functional tests (specifically flow tests) pass
> Gremlin traversal ctor

- contrib/python/api/setup.py
- contrib/python/api/skydive/rest/client.py
- contrib/python/api/skydive/websocket/client.py
- contrib/python/api/skydive/wsshell.py
- contrib/python/api/tests/tests.py
- http/auth.go
- http/basic.go
- http/keystone.go
- http/noauth.go
- http/server.go
- scripts/ci/install-static-requirements.sh
- scripts/ci/run-python-tests.sh
http : fix Basic Auth, as the server need to reply WWW-Authenticate on 401
python : client support auth and SSL/TLS connection
> python : client support auth and SSL/TLS connection

- topology/probes/socketinfo/connection.go
> socket: do not modify node metadata to decode flow protocol

- http/wsmessage_test.go
- http/wsserver_test.go
Server wait a first message from
client before sending messages to
it in order to be sure that the
client is ready to consume them.
> test: fix http subscription tests

- cmd/allinone/allinone.go
- cmd/analyzer/analyzer.go
- cmd/client/client.go
- cmd/config/config.go
- cmd/skydive/skydive.go
config : try loading default configuration file /etc/skydive/skydive.yml 
if no parameter is given, will not fail starting skydive if the file didn't exist
client : read auth config from configuraiton file if not already set
> Try loading default config file if none are given

- etc/skydive.yml.default
- statics/js/components/topology.js
… default and applied on WebUI load)
> ui: add support for default_filter

- contrib/python/api/setup.py
To create a new distribution package
> Bump up the python client version to 0.4.4

- contrib/python/api/setup.py
- contrib/python/api/skydive/rest/client.py
Note I did not run the included python tests suite (even if I tryied a bit):/
> python: add capture API

- statics/css/skydive.css
- statics/index.html
- statics/js/components/routing-table.js
- statics/js/components/topology.js
This display the routing tables in a nicer way
> ui: add routing-table component

- Makefile
some of the top-level Makefile were not set as .PHONY (issues discovered on the devmode environment) , this has been addressed in this PR.
> build: add .PHONY to all phony targets on top-level makefile

- scripts/ci/ansible/deploy.yml
o service enable: yes (not true)
o reboot slaves after install aim to match running kernel with devel headers
o pause jenkins_master only on deploy_master
> ansible : fix service, reboot slaves, pause jenkins_master

- scripts/ci/jobs/jobs.yml
> CI : skip jobs on PR comment

- Makefile
make functional : defaulting to run with elasticsearch database
> Makefile : make functional : defaulting to run with elasticsearch DB

- etc/skydive.yml.default
ES specific configuration need to be keep in storage.elasticsearch section
> ES : fix configuration

- scripts/ci/install-minikube.sh
to test run:
```
./install-minikube.sh install
./install-minikube.sh start
./install-minikube.sh status
```
Unfortunately localkube is still consuming unlimited memory
> minikube: upgrade to new version

- statics/js/app.js
- statics/js/components/capture-list.js
- statics/js/components/flow-table.js
- statics/js/components/injection-list.js
when moving quickly on highlight link
node is not unhighlighted
> ui: fix unhighlight issue of nodes

- contrib/ansible/roles/skydive_dev/tasks/lxd.yml
- contrib/ansible/roles/skydive_dev/tasks/main.yml
- scripts/ci/cleanup.sh
- scripts/ci/devstack/Vagrantfile
- scripts/ci/install-helm.sh
- scripts/ci/kolla/run-kolla.sh
skip skydive-go-fmt skydive-unit-tests skydive-compile-tests skip skydive-functional-tests-backend-elasticsearch skydive-functional-tests-backend-orientdb skip skydive-scale-tests skip skydive-selenium-tests
> ci: use fedora 27 for devstack

- statics/js/components/rule-detail.js
* Make priority of the rule a separated column.
* Rules of same priority share a single priority cell spanning multiple
rows.
* Rules with the same set of actions share a single cell spanning
multiple rows (They have different filters).
Closes #970
> ui,oflow: group openflow rules by priority and actions

- contrib/vagrant/Vagrantfile
skip skydive-cdd-overview-tests skip skydive-coverage skip skydive-devstack-tests skip skydive-helm-tests skip skydive-kolla-tests skip skydive-skydive-release skip skydive-create-binaries skip skydive-compile-tests skip skydive-functional-tests-backend-elasticsearch skip skydive-functional-tests-backend-orientdb skip skydive-go-fmt skip skydive-k8s-tests skip skydive-packaging-tests skip skydive-python-tests skip skydive-scale-tests skip skydive-selenium-tests skip skydive-unit-tests
> vagrant: fix installation of openvswitch

- contrib/ansible/roles/skydive_common/tasks/package.yml
use centos opstools release package to setup the repo with gpg signature check
> ansible : use centos opstools release package

- contrib/ansible/roles/skydive_dev/tasks/fedora.yml
- contrib/ansible/roles/skydive_dev/tasks/main.yml
- contrib/dev/Vagrantfile
devmode: fix vagrant virtualbox (plugin, ansible, chmod, doc)
- plugin: added missing plugin dependencies
- ansible: we map ansible guest to ../../contrib/ansible
> devmode: fix vagrant virtualbox (deps, chmod, doc)

- contrib/ansible/README.md
- contrib/ansible/roles/skydive_agent/defaults/main.yml
- contrib/ansible/roles/skydive_agent/tasks/main.yml
- contrib/ansible/roles/skydive_analyzer/defaults/main.yml
- contrib/ansible/roles/skydive_analyzer/tasks/config.yml
- contrib/ansible/roles/skydive_analyzer/tasks/main.yml
- contrib/ansible/roles/skydive_common/defaults/main.yml
- contrib/vagrant/Vagrantfile
- etcd/server.go
- scripts/ci/run-vagrant-tests.sh
now generated from the analyzers list
> ansible: fix etcd server list

- devstack/local.conf.cpu
- devstack/local.conf.full
- devstack/plugin.sh
> devstack: fix etcd listen and server address

- Makefile
- scripts/ci/install-helm.sh
- scripts/ci/install-minikube.sh
- scripts/ci/run-helm-tests.sh
- scripts/ci/run-k8s-tests.sh
- tests/helm_test.go
add minimal test for helm which should be invoked when setting the `WITH_K8S` during build
> helm: added a minimal install/delete test

- etc/skydive.yml.default
- topology/probes/k8s/cluster.go
- topology/probes/k8s/namespace.go
To check configure all elements for example by:
```
k8s:
probes:
```
Now create the hello-node landscape using:
```
kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
```
Now check that UI is ok (all elements are tied to cluster or indirectly to namespace).
> K8s edges fix

- scripts/ci/jobs/jobs.yml
skip skydive-go-fmt skip skydive-functional-tests-backend-elasticsearch skip skydive-functional-tests-backend-orientdb skip skydive-scale-tests skip skydive-selenium-tests skip skydive-unit-tests skip skydive-compile-tests skip skydive-k8s-tests
> ci: add contrail job

- gremlin/query.go
- tests/k8s_test.go
- topology/probes/k8s/cluster.go
simply make sure that k8s tests run, when developing the tests I discovered some issues with links:
- cluster --> node
- node --> pod
So for now (until fixing the k8s probe) these were eliminated from the test scenario
> K8s hellonode scenario

- tests/helper/helper.go
- tests/selenium_test.go
- tests/tests.go
skip skydive-go-fmt skip skydive-functional-tests-backend-elasticsearch skip skydive-functional-tests-backend-orientdb skip skydive-scale-tests skip skydive-unit-tests skip skydive-compile-tests skip skydive-k8s-tests
> tests: add basic selenium for agent Web UI

- Makefile
- contrib/ansible/roles/skydive_dev/tasks/main.yml
- contrib/packaging/rpm/generate-skydive-bootstrap.sh
- contrib/packaging/rpm/skydive.spec
- scripts/ci/ansible/deploy.yml
- scripts/ci/run-packaging-tests.sh
skip skydive-go-fmt skip skydive-functional-tests-backend-elasticsearch skip skydive-functional-tests-backend-orientdb skip skydive-scale-tests skip skydive-selenium-tests skip skydive-unit-tests skip skydive-compile-tests skip skydive-k8s-tests
> tests: run packaging tests against CentOS and Fedora

- contrib/vagrant/playbook-es.yml
> vagrant: fix ansible playbook ElasticSearch

- contrib/ansible/roles/skydive_common/tasks/systemd.yml
> ansible: ensure the services are restarted

- tests/k8s_test.go
- topology/probes/k8s/graph.go
- topology/probes/k8s/pod.go
Adding new fields to Pod:
- IP (optional)
- Status
- Node
The mandatory fields are verified via functional test - so if this passes functional we should be ok
> K8s metadata pod

- config/config.go
The port used by the client if no
server list was provided was hard coded
and not using the listen port.
> etcd: fix embedded etcd custom port

- agent/agent.go
- analyzer/server.go
- flow/storage/elasticsearch/elasticsearch.go
- gremlin/traversal/descendants.go
- gremlin/traversal/flows.go
- gremlin/traversal/rawpackets.go
- gremlin/traversal/token.go
- tests/flow_test.go
- topology/graph/traversal/traversal_parser.go
- topology/topology_subscriber_endpoint.go
- validator/validator.go
returns the nodes selected plus the
children following Ownership links.
> gremlin: add descendants step

- tests/k8s_test.go
- topology/probes/k8s/container.go
- topology/probes/k8s/graph.go
- topology/probes/k8s/pod.go
Added following fields to the container (plus extended test)
- Image:
- PodName
- PodNamespace
- PodLabels
> K8s metadata container

- tests/k8s_test.go
- topology/probes/k8s/namespace.go
Added these fields to namespace object:
- Cluster
- Labels
- Status
> k8s: enhance namespace object

- contrib/ansible/roles/skydive_common/tasks/package.yml
- contrib/packaging/rpm/skydive.spec
- scripts/ci/run-vagrant-tests.sh
> packaging: fix policyutils dependency

- topology/graph/graph.go
- topology/graph/graph_test.go
Need to verify all tests still pass
> graph: fixed major bug in GetFirstLink()

- scripts/ci/create-docker-image.sh
I'm assuming the proxy is set as env http_proxy in the ci environment
> docker/ci: use proxy only if http_proxy is set

- topology/graph/traversal/traversal.go
- topology/graph/traversal/traversal_parser.go
- topology/graph/traversal/traversal_scanner.go
This allows to do a kind of "or"
Now we can merge two results
G.V().Has("Type", "netns").descendants().as("ns").\
G.V().Has("Type", "host").as("host").\
select("ns", "host").subgraph()
> gremlin: add as/select steps

- common/types.go
- topology/graph/graph.go
- topology/probes/k8s/container.go
- topology/probes/k8s/namespace.go
- topology/probes/k8s/networkpolicy.go
- topology/probes/k8s/node.go
- vendor/vendor.json
Addresses: https://github.com/skydive-project/skydive/issues/1195
> K8s metadata deepcopy

- vendor/vendor.json
upgrade all packages under k8s.io from kubernetes-1.8.1 to kubernetes-1.9.1
to verify PR just check is that all CI tests pass
> Vendor k8s io

- contrib/ansible/roles/skydive_agent/tasks/docker.yml
- contrib/ansible/roles/skydive_common/tasks/config.yml
- contrib/vagrant/Vagrantfile
- contrib/vagrant/setup-common.sh
- gremlin/query.go
- scripts/ci/run-vagrant-tests.sh
- tests/alert_test.go
- tests/flow_test.go
- tests/helper/helper.go
- tests/lxd_test.go
- tests/openflow_test.go
- tests/startup_capture_test.go
- tests/tests.go
- tests/topology_test.go
- topology/graph/traversal/traversal.go
- topology/probes/netns/netns.go
- topology/probes/ovsdb/ovs_of.go
> CI : run functional tests in vagrant

- tests/k8s_test.go
- topology/probes/k8s/ingress.go
Test by running the below and checking the UI:
```
kubectl create -f tests/k8s/ingress.yaml
```
> k8s: add ingress metadata fields

- tests/k8s_test.go
- topology/probes/k8s/job.go
Test running the below and checking the UI:
```
kubectl create -f tests/k8s/job.yaml
```
> k8s: add job metadata fields

- config/config.go
- tests/opencontrail_test.go
- topology/probes/opencontrail/opencontrail.go
- topology/probes/opencontrail/routing_table.go
- topology/probes/ovsdb/ovs_of.go
- topology/probes/ovsdb/ovsdb.go
> Stop command using context

- tests/k8s_test.go
- topology/probes/k8s/service.go
To test run the below and verify using UI:
```
kubectl create -f tests/k8s/statefulset.yaml
```
> k8s: service metadata

- tests/k8s/ingress1.yaml
- tests/k8s_test.go
- topology/probes/k8s/ingress.go
WIP: no need to review at this phase
to view you can run:
```
kubectl create -f tests/k8s/ingress1.yaml
```
> k8s: ingress links

- contrib/ansible/roles/skydive_dev/tasks/main.yml
- scripts/ci/install-minikube.sh
To test just ensure k8s test passes.
> minikube: upgrade to v0.28.2

- contrib/ansible/roles/skydive_dev/tasks/main.yml
- scripts/ci/install-minikube.sh
Reverts skydive-project/skydive#1259
> Revert "minikube: upgrade to v0.28.2"

- scripts/ci/ansible/deploy.yml
- scripts/ci/install-minikube.sh
- scripts/ci/jobs/jobs.yml
- tests/k8s_test.go
> Minikube driver

- .gitreview
> git: remove gitreview file

- api/types/types.go
- cmd/client/edgerule.go
- cmd/client/noderule.go
- topology/enhancers/topology_manager.go
- validator/validator.go
new gremlin or empty validator
new name description fields for rules
name and type changed to node-name and node-type respectively
> Topology api validator changes 

- contrib/ansible/library/skydive_edge.py
- contrib/ansible/library/skydive_node.py
This exposes the skydive API through ansible
> ansible: introduce skydive library

- scripts/ci/jobs/jobs.yml
> ci: send email when deliverables failed to build

- scripts/ci/ansible/deploy.yml
> ci: configure sudo for Vagrant NFS synced folders

- scripts/ci/run-tripleo-tests.sh
- scripts/ci/tripleo-quickstart/minimal.yml
- scripts/ci/tripleo-quickstart/skydive-minimal.yaml
- scripts/ci/tripleo-tests.sh
- scripts/test.sh
> tripleo: use test.sh for testing for more complete test suite

- topology/probes/istio/destinationrule.go
- topology/probes/istio/istio.go
- vendor/vendor.json
just verify tests run as before
> istio: vendoring set to github.com/kiali/kiali/kubernetes

- analyzer/probes.go
- tests/k8s_test.go
- topology/probes/istio/destinationrule.go
- topology/probes/istio/graph.go
- topology/probes/k8s/container.go
- topology/probes/k8s/cronjob.go
- topology/probes/k8s/daemonset.go
- topology/probes/k8s/deployment.go
- topology/probes/k8s/endpoints.go
- topology/probes/k8s/graph.go
- topology/probes/k8s/ingress.go
- topology/probes/k8s/job.go
- topology/probes/k8s/namespace.go
- topology/probes/k8s/networkpolicy.go
- topology/probes/k8s/node.go
- topology/probes/k8s/persistentvolume.go
- topology/probes/k8s/persistentvolumeclaim.go
- topology/probes/k8s/pod.go
- topology/probes/k8s/probe.go
- topology/probes/k8s/replicaset.go
- topology/probes/k8s/replicationcontroller.go
- topology/probes/k8s/service.go
- topology/probes/k8s/statefulset.go
- topology/probes/k8s/storageclass.go
many small fixes left over from the k8s refactor PR.
only minor behavior changes, integrity can be verified by checking all tests still pass
> K8s post refactor

- topology/probes/k8s/service.go
fixed a bug causing in some cases to disregard the service object pod-selector as a result creating links between the service to all the pods within its' namespace.
to verify run and check in the UI that:
- kube-dns(service) is connected to a single pod
- kube-dashboard(service) is connected to a single pod
> k8s: service-pod linkes refine

- contrib/python/api/skydive/auth.py
- contrib/python/api/skydive/rest/client.py
- contrib/python/api/skydive/websocket/client.py
> python: allow passing cookies for request

- Makefile
- api/types/types.go
- cmd/client/capture.go
- common/types.go
- common/types_test.go
- contrib/ansible/roles/skydive_dev/tasks/protobuf.yml
- filters/filters.go
- flow/flow.go
- flow/flow.proto
- flow/flow_test.go
- flow/layers/layers.go
- flow/probes/probes.go
- flow/table.go
- ovs/ovsdb.go
- statics/js/components/capture-list.js
- validator/validator.go
- vendor/vendor.json
- websocket/message.go
- websocket/message_test.go
This add capability to add
extra layers to flows
> flow: add extra layers

- contrib/charts/templates/deployment-agents.yaml
- contrib/charts/templates/deployment-analyzer.yaml
- contrib/kubernetes/skydive.yaml
- contrib/openshift/skydive-template.yaml
> Fix helm, k8s and openshift templates

- statics/js/components/topology.js
to test run skydive with k8s probe enabled and verify that you get a list of filters (such as filter services, network, compute, storage, etc.)
> k8s: add type based filters

- Makefile
- contrib/ansible/roles/skydive_common/tasks/package.yml
- contrib/packaging/rpm/skydive.spec
- scripts/ci/run-vagrant-tests.sh
> packaging: remove skydive-ansible dependency on skydive

- contrib/snort/Makefile
to test run:
```
make
make clean
```
> Snort make clean

- statics/workflows/check-connectivity.yaml
> workflows: add check connectivity workflow

- contrib/vagrant/Vagrantfile
- scripts/ci/run-vagrant-tests.sh
- scripts/test.sh
> test: fix vagrant tests

- contrib/kubernetes/skydive.yaml
- contrib/openshift/skydive-template.yaml
> Openshift config maps

- tests/istio_test.go
Extend istio's test with Bookinfo scenario. 
For testing, simply run the test.
> istio: add destinationrule test

- topology/probes/k8s/probe.go
all internal k8s errors are now redirected to `logging.getLogger().Debug()`
> k8s: throttle internal k8s errors

- contrib/ansible/roles/elasticsearch/tasks/main.yml
- contrib/ansible/roles/skydive_dev/tasks/gimme.yml
- contrib/ansible/roles/skydive_dev/tasks/protobuf.yml
- contrib/dev/Vagrantfile
- scripts/ci/create-vagrant-boxes.sh
> devmode: do not put GOROOT inside GOPATH

- contrib/openshift/README.md
In #1446 was the question answered how to add the skydive nodes to all nodes. This PR reflects the solution in the README
> Run skydive agents on all nodes

- agent/agent.go
- analyzer/flow_client.go
- analyzer/flow_server.go
- analyzer/flow_subscriber_endpoint.go
- analyzer/server.go
- rbac/policy.csv
- scripts/ci/run-opencontrail-tests.sh
- websocket/message.go
This aims to provide a way to get flow
in through websocket endpoint. It supports
flow as JSON or Protobuf according to the given
protocol of the client.
> flow: introduce flow stream endpoint

- Makefile
- contrib/docker/Dockerfile.compile
Signed-off-by: Mathieu Rohon <mathieu.rohon@orange.com>
> Build: save previous compilation results

- scripts/ci/jobs/jobs.yml
- tests/k8s_test.go
- topology/probes/istio/destinationrule.go
- topology/probes/istio/gateway.go
- topology/probes/istio/istio.go
- topology/probes/istio/quotaspec.go
- topology/probes/istio/quotaspecbinding.go
- topology/probes/istio/serviceentry.go
- topology/probes/istio/virtualservice.go
- topology/probes/k8s/cluster.go
- topology/probes/k8s/container.go
- topology/probes/k8s/cronjob.go
- topology/probes/k8s/daemonset.go
- topology/probes/k8s/deployment.go
- topology/probes/k8s/endpoints.go
- topology/probes/k8s/ingress.go
- topology/probes/k8s/job.go
- topology/probes/k8s/k8s.go
- topology/probes/k8s/namespace.go
- topology/probes/k8s/networkpolicy.go
- topology/probes/k8s/node.go
- topology/probes/k8s/persistentvolume.go
- topology/probes/k8s/persistentvolumeclaim.go
- topology/probes/k8s/pod.go
- topology/probes/k8s/probe.go
- topology/probes/k8s/replicaset.go
- topology/probes/k8s/replicationcontroller.go
- topology/probes/k8s/service.go
- topology/probes/k8s/statefulset.go
- topology/probes/k8s/storageclass.go
broken due to changes done in topology/graph/graph.go
maybe we should consider re-adding k8s tests to list of defaults
> k8s: fixed compilation of tests

- contrib/ansible/library/skydive_edge.py
- contrib/ansible/library/skydive_node.py
Generates a host_id based on the host parameter. Necessary to avoid
conflicts on the analyzer.
Adds some notes and fixes some minor problems in the online
documentation.
closes #1484
> ansible: bug - different websocket host_id

- statics/js/components/rule-detail.js
* Use the real graph as BridgeLayout support structure.
* Fix filter computed for multiple values of a single field.
> ui: fix bugs in OpenFlow rule filters

- statics/js/components/workflow.js
added a loading icon till workflow return a result
> ui: improvement in workflow tab

- contrib/python/api/skydive/alerts.py
- contrib/python/api/skydive/rest/client.py
- contrib/python/api/tests/tests.py
> Add alert to python rest api

- contrib/ansible/library/skydive_edge_list.py
- contrib/ansible/library/skydive_node_list.py
Provides actions on lists  of elements that are much faster
than repeating actions on one element at a time.
> ansible: actions on list of elements

- contrib/python/api/skydive/captures.py
- contrib/python/api/skydive/rest/client.py
- contrib/python/api/tests/tests.py
Co-authored-by: Darshan Vandra <dvandra.ai@gmail.com>
> Python:Adding testcase for API support for capture

- api/types/types.go
- cmd/client/packet_injector.go
- packetinjector/client.go
- packetinjector/forge.go
- packetinjector/inject_packet.go
- statics/js/components/inject-form.js
increase the packets' payload on each packet
> pi: increase packets' payload

- devstack/plugin.sh
> devstack: introduce install modes: source, binary, release

- topology/probes/netns/netns.go
- topology/probes/runc/runc.go
prior to this commit it was string
75d98b26b7acb0023b990a7305a2553c6dbc12d4
> runc: handle string or int64 for init_process_pid

- topology/probes/docker/docker.go
- topology/probes/runc/runc.go
There was a race between runc and docker probes
on the Manager metadata.
> docker: fix race between runc when docker uses libcontainer

- packetinjector/forge.go
set ttl in icmpv4 injection to 64 instead of 0
> set ttl in icmpv4 injection

- tests/k8s_test.go
- topology/probes/k8s/cache.go
- topology/probes/k8s/deployment.go
- topology/probes/k8s/ingress.go
- topology/probes/k8s/k8s.go
- topology/probes/k8s/linker.go
- topology/probes/k8s/networkpolicy.go
- topology/probes/k8s/service.go
the networkpolicy was using CreateEdge() rather than NewEdge() as a result edges were often not being added to the graph, making k8s tests flaky.
> K8s netpol linker

- statics/js/components/object-detail.js
This reverts commit 5ed795b34692ee65953bdbf7941770b4f6dee6fa.
> Revert "ui: don't show the collapse icon for an empty object"

- scripts/ci/install-go.sh
- scripts/ci/jobs/jobs.yml
> ci: share compile cache

- tests/istio_test.go
This PR contains the complete bookinfo scenario for testing Istio.
> istio: update bookinfo scenario

- skydive_prof.go
> profiling: add memory profiling signal handler

- topology/probes/istio/virtualservice.go
This PR updates the mechanism that creates links between virtualservice and pod, based on #1543.
> istio: update virtualservice-pod linker

- topology/probes/ovsdb/ovs_of.go
- topology/probes/ovsdb/ovs_of_test.go
Missing wait for execcommandpipe.
Closes: #1541
> openflow: bug - probe creates zombies

- scripts/ci/create-vagrant-boxes.sh
> ci: create the vagrant version and providers

- contrib/ansible/library/skydive_query.py
Sends a gremlin query to a skydive analyzer, the result is a list of
nodes/edges in json format.
> ansible: simple module to query skydive

- contrib/packaging/rpm/skydive.spec
skip skydive-functional-tests-ebpf
Remaining warning..
```
(Thu Jan 17 09:44:57:703083 2019) [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Could not open available domains
groupadd: sss_cache exited with status 5
groupadd: Failed to flush the sssd cache.
(Thu Jan 17 09:44:57:714083 2019) [sss_cache] [confdb_init] (0x0010): Unable to open config database [/var/lib/sss/db/config.ldb]
Could not open available domains
groupadd: sss_cache exited with status 5
groupadd: …
```
> packaging: make working with RHEL8

- analyzer/flow_subscriber_endpoint.go
- contrib/objectstore/subscriber/objectstore.go
> objectstore: specify protobuf as client protocol

- Makefile
- analyzer/server.go
- api/client/gremlin.go
- flow/probes/ovssflow.go
- flow/probes/sflow.go
- gremlin/query.go
- gremlin/traversal/metrics.go
- gremlin/traversal/topology.go
- sflow/agent.go
- sflow/sflowmetric.go
- sflow/sflowmetric_test.go
- statics/js/components/metrics-table.js
- statics/js/components/topology.js
- tests/flow_test.go
- tests/topology_test.go
- vendor/vendor.json
Co-authored-by: Asma Suhani <suhu118415@gmail.com>
> Adding OVS-SFlow Metric to Metadata

- statics/js/components/topology.js
This PR adds a new istio filter that shows k8s and istio objects which are related to network.
> ui: add istio network filter

- statics/js/app.js
- statics/js/components/graph-layout.js
- statics/js/components/topology.js
Signed-off-by: Mathieu Rohon <mathieu.rohon@orange.com>
> ui: Emphasize edges

- tests/lxd_test.go
skip skydive-functional-tests-ebpf
> tests: change lxd image to ubuntu bionic

- packetinjector/client.go
automatically select neutrons' IP and MAC for neutron nodes.
> pi: select neutrons' IP and MAC for neutron nodes

- contrib/ansible/roles/elasticsearch/tasks/main.yml
- contrib/ansible/roles/skydive_dev/tasks/main.yml
- scripts/ci/cleanup.sh
- scripts/ci/create-vagrant-boxes.sh
skip skydive-functional-tests-ebpf
> ansible: replace yum-utils by dnf-utils

- statics/css/graph-layout.css
This PR changes istio edges color so they will be easily recognizable.
> istio: change edges color

- README.md
skip skydive-functional-tests-ebpf
> README.md: update badges

- contrib/ansible/roles/skydive_dev/defaults/main.yml
- contrib/ansible/roles/skydive_dev/tasks/virtualbox.yml
- scripts/ci/jobs/jobs.yml
> ci: fix vagrant boxes by defining skydive_container_cli

- tests/k8s_test.go
to verify this works just time here:
```
run skydive-k8s-tests
```
> k8s/tests: apply and delete of contrib/kubernetes/skydive.yaml

- scripts/ci/create-docker-image.sh
NOTE: based on top of #1651 
IBM Cloud (and other projects) need to be able to consume skydive releases continuously as opposed to the just restricted to "official release" or "latest". The proposal is that skydive continuously uploads current docker images to `hub.docker.com/skydive/snapshots`.
So on each commit skydive ci would push the following images:
```
skydive/skydive:latest
skydive/snapshots:0.21.0-123456789012
skydive/snapshots:0.21.0-123456789012-linux-s390x
skydive/snapshots:0.21.0-123456789012-linux-ppc64le
skydive/snapshots:0.21.0-123456789012-linux-amd64
```
And as to the consideration of running out of storage on docker hub. The expected storage requirement is `100MB x 3 (architectures) x 3000 (commits) = 1TB`  given that docker hub supports multi GB singe docker images it …
> ci: create docker image snapshots per-commit

- flow/probes/ebpf.go
- probe/ebpf/flow.c
- probe/ebpf/flow.h
Hi all, 
following a previous PR where we introduced this idea, we here add extra TCP flags to Skydive's reported flows with ebpf
> Tcp extra flags

- contrib/objectstore/main.go
- contrib/objectstore/skydive-objectstore.yml.default
- contrib/objectstore/subscriber/client.go
- vendor/vendor.json
Adding support for IBM IAM OAuth authentication for IBM Cloud Object Storage.
> add IBM IAM OAuth support

- contrib/ansible/roles/skydive_analyzer/tasks/config.yml
- contrib/ansible/roles/skydive_analyzer/tasks/iptables.yml
- scripts/ci/run-vagrant-tests.sh
due to python 3.7 issue : https://bugs.python.org/issue32308
> ansible: workaround regex

- topology/probes/istio/virtualservice.go
This PR adds edge from virtualservice to pods that TLS, TCP traffic is being routed to by this virtualservice.
> istio: support TLS, TCP traffic routing by virtualservice

- contrib/objectstore/subscriber/objectstore.go
- contrib/objectstore/subscriber/objectstore_test.go
- contrib/objectstore/subscriber/secadvisor.go
Made some changes to the format of flows required by security advisor.
> security advisor flow format changes

- flow/probes/ebpf.go
- flow/table.go
> fix update of TCPMetrics

- contrib/ansible/roles/skydive_analyzer/tasks/config.yml
- contrib/tripleo/skydive-tripleo-inventory
> Fix ansible etcd listen

- topology/probes/istio/virtualservice.go
This PR fixes the way virtualservices weights are being calculated.
Note that only the default weights (which appear in an unconditional routing rules) are taken into account.
> istio: fix virtualservice weight calculation

- contrib/objectstore/main.go
- contrib/objectstore/skydive-objectstore.yml.default
- contrib/objectstore/subscriber/client.go
- contrib/objectstore/subscriber/flowclassifier.go
- contrib/objectstore/subscriber/flowtransformer.go
- contrib/objectstore/subscriber/objectstore.go
- contrib/objectstore/subscriber/objectstore_test.go
- contrib/objectstore/subscriber/secadvisor.go
- contrib/objectstore/subscriber/subscriber.go
Hi @safchain 
In this PR we make a change to our `custom1` flow transformer to include container names (via the runc probe).
Thanks in advance!
> add container name fields to custom flow transformer

- Makefile
- flow/probes/ebpf.go
- probe/ebpf/Makefile
- probe/ebpf/bpf.h
- probe/ebpf/flow.c
- probe/ebpf/flow.h
- probe/ebpf/flow_network.c
- tests/flow_ebpf_test.go
- tests/flow_test.go
- vendor/vendor.json
> flow: eBPF IP/GRE support

- contrib/docker/Dockerfile.crosscompile
run skydive-create-docker-image
> docker: cross-compile add bionic-updates repository to resolve missing packages

- scripts/ci/create-docker-image.sh
> ci: create-docker-image.sh cross compiles have BASE

- Makefile
to test:
```
rm flow/layers/generated.proto
make clean
```
failed before will succeed now
> make: fix proto clean

- api/types/types.go
- cmd/client/capture.go
- flow/probes/ovssflow.go
- statics/js/components/capture-form.js
- tests/flow_test.go
- tests/tests.go
- tests/topology_test.go
Advanced options for "ovssflow" Capture Type : 
Options to add sampling rate and polling counters.
> Add advanced options for ovssflow capture type

- api/types/types.go
- tests/tests.go
> tests: remove injections at the end of the test

- statics/js/components/graph-layout.js
- statics/js/components/topology.js
Signed-off-by: Mathieu Rohon <mathieu.rohon@orange.com>
> ui: add an arrow for links with the metadata Directed=true

- CHANGELOG.md
- contrib/ansible/roles/skydive_common/defaults/main.yml
- contrib/packaging/rpm/skydive.spec
- contrib/packaging/rpm/skydive.te.fedora
- contrib/packaging/rpm/skydive.te.rhel
- scripts/ci/create-vagrant-boxes.sh
> Bump to version 0.23

- contrib/ansible/roles/skydive_analyzer/tasks/config.yml
- contrib/ansible/roles/skydive_analyzer/tasks/container.yml
- contrib/ansible/roles/skydive_common/tasks/container.yml
- contrib/ansible/roles/skydive_common/tasks/permissions.yml
> Fix ansible volume n tag

- api/server/pcap.go
- flow/ebpf.go
- flow/flow.go
- flow/flow_test.go
- flow/hash.go
- flow/no_ebpf.go
- flow/probes/ebpf.go
- flow/probes/pcapsocket.go
- flow/table.go
- flow/table_test.go
- gremlin/traversal/cflows.go
- gremlin/traversal/flow_test.go
- sflow/agent.go
- vendor/vendor.json
Hi guys,
as promised this commit includes a few changes. 
Flow table is now bounded - no memory leaks
Hash function was replaced - no collisions 
Only one copy of the flow table is kept in ebpf now
This is still the first commit. Still need to report the number of deleted flows so this is on our todo list.
Cheers
> flow : use xxHash and eBPF fixies

- statics/js/components/topology.js
> ui: use default filter if not filter given and fix resync

- contrib/ansible/roles/orientdb/tasks/main.yml
> ansible: fix orientdb url

- websocket/server_test.go
To verify this works just run tests:
```
cd websocket
go test
```
> websocket: test multiple clients with host_id=""

- contrib/ansible/library/skydive_query.py
- contrib/charts/Chart.yaml
- contrib/objectstore/subscriber/client.go
- contrib/objectstore/subscriber/objectstore_test.go
- contrib/openshift/README.md
- flow/allocator.go
- graffiti/cmd/pod.go
- graffiti/graph/graph.go
- graffiti/graph/sort.go
- graffiti/graph/traversal/traversal.go
- gremlin/traversal/nexthop.go
- js/runtime.go
- probe/ebpf/flow.h
- statics/js/websocket.js
- topology/probes/libvirt/libvirt.go
- topology/probes/netlink/netlink.go
- topology/probes/netlink/sriov.go
- topology/probes/nsm/nsm_test.go
- topology/probes/ovn/ovn.go
- topology/probes/ovsdb/jsonof/ovs_rule_parser.go
- topology/probes/runc/metadata.go
- topology/probes/vpp/vpp.go
- websocket/server.go
> Fix mispells

- config/config.go
- etc/skydive.yml.default
- flow/probes/ebpf.go
- flow/table.go
- probe/ebpf/flow-gre.c
- probe/ebpf/flow.c
Warns upon flows being dropped from the flow table due to overflows
> added statistics for dropped flows from flow table

- contrib/ansible/roles/skydive_agent/tasks/container.yml
- contrib/tripleo/skydive-tripleo-inventory
> ansible: fix keystone v3 auth in skydive tripleo inventory

- cmd/client/packet_injector.go
- cmd/injector/standalone.go
- common/common.go
- packetinjector/client.go
- packetinjector/forge.go
- packetinjector/inject_packet.go
- packetinjector/server.go
With this, you can generate traffic without starting a skydive.
currently, it has some limitations and hardcoded values.
needed some improvements.
> pi: standalone packet injector

- api/server/workflow_runtime.go
- js/api.ts
- js/runtime.go
- statics/workflows/check-connectivity.yaml
- statics/workflows/flow-validation.yaml
- tests/workflow_test.go
Checks Packet Forwarding between Checkpoint-1 and Checkpoint-2:
Capture - To Capture Specific Type of Traffic using BPF-Filter
> Packet Flow Validation Workflow

- websocket/client.go
> websocket: use correct data frame encoding opcode

- statics/js/components/rule-detail.js
> Fix ofrule tab reset

- api/types/types.go
- statics/css/skydive.css
- statics/js/components/workflow.js
- statics/workflows/check-connectivity.yaml
- statics/workflows/check-mtu.yaml
- statics/workflows/flow-matrix.yaml
- statics/workflows/flow-validation.yaml
Adding "Help" and "How It Works" in Skydive Workflow in-order to make it more generic and user-friendly.
> Workflow: Add "Help" and "How It Works"

- CHANGELOG.md
- contrib/ansible/roles/skydive_common/defaults/main.yml
- contrib/packaging/rpm/skydive.spec
- contrib/packaging/rpm/skydive.te.fedora
- contrib/packaging/rpm/skydive.te.rhel
- scripts/ci/create-vagrant-boxes.sh
> Bump to version 0.24.0

- contrib/pipelines/dummy/main.go
- contrib/pipelines/secadvisor/Makefile
- contrib/pipelines/secadvisor/README.md
- contrib/pipelines/secadvisor/main.go
- contrib/pipelines/secadvisor/secadvisor.yml.default
to test one can follow the readme
> secadvisor: complete README and minor fixes

- contrib/ansible/roles/skydive_dev/tasks/ci.yml
- scripts/ci/create-binaries.sh
> ci: install lfs hooks

- contrib/pipelines/awsflowlogs/Makefile
- contrib/pipelines/awsflowlogs/awsflowlogs.yml.default
- contrib/pipelines/awsflowlogs/main.go
- contrib/pipelines/awsflowlogs/transform.go
- contrib/pipelines/core/Makefile
- contrib/pipelines/core/compress.go
- contrib/pipelines/core/encode.go
- contrib/pipelines/core/store.go
- contrib/pipelines/core/store_s3.go
- contrib/pipelines/core/store_s3_test.go
- contrib/pipelines/core/store_stdout.go
- contrib/pipelines/core/transform.go
- contrib/pipelines/dummy/main.go
- contrib/pipelines/secadvisor/transform.go
- contrib/pipelines/secadvisor/transform_test.go
- vendor/vendor.json
@lebauce / @safchain  / @nplanel - code not ready yet for review/merge
@eranra / @andrekassis - please provide some preliminary feedback
> Pipeline: AWS Flow Logs

- Makefile
- contrib/docker/Dockerfile.compile
- contrib/docker/Dockerfile.crosscompile
- scripts/ci/create-docker-image.sh
- scripts/ci/run-compile-tests.sh
- scripts/ci/run-tests-utils.sh
> build: fix build of docker images

- flow/probes/ebpf.go
- vendor/vendor.json
o need an upstream patch to avoid memcpy
o need for fastest functional test
> ebpf : use github.com/newtools/ebpf package

- contrib/kubernetes/skydive.yaml
I had to add this so the agents transition to ready state.
Ref. #1895
> Listen to 0.0.0.0 to reach ready state

- contrib/exporters/awsflowlogs/awsflowlogs.yml.default
- contrib/exporters/core/subscriber.go
- contrib/exporters/secadvisor/secadvisor.yml.default
- contrib/exporters/vpclogs/vpclogs.yml.default
- flow/server/flow_subscriber_endpoint.go
- websocket/message_test.go
add websocket registration server side filtering by capture_id
> Pipeline: added subscribe to flows by capture_id

- topology/probes/runc/runc.go
> runc: improve a bit error message when getting ns handler

- statics/workflows/flow-validation.yaml
Add Capture Validator : If any Node/Interface is DOWN - Capture will not be created on that node and no flows will be captured on that node.
> Fix Flow-Validation workflow : Add Capture Validator

- .mk/api.mk
- .mk/bench.mk
- .mk/bindata.mk
- .mk/check.mk
- .mk/contrib.mk
- .mk/debug.mk
- .mk/dist.mk
- .mk/easyjson.mk
- .mk/gendecoder.mk
- .mk/proto.mk
- .mk/static.mk
- .mk/tests.mk
- .mk/vppapi.mk
- Makefile
- contrib/ansible/roles/skydive_dev/tasks/ci.yml
- contrib/ansible/roles/skydive_dev/tasks/gimme.yml
- contrib/dev/Vagrantfile
- flow/probes/ebpf.go
- probe/ebpf/Makefile
- scripts/ci/cleanup.sh
- scripts/ci/create-vagrant-boxes.sh
- scripts/ci/jobs/jobs.yml
- scripts/scale.sh
- tests/api_test.go
- websocket/server.go
> Fix vagrant dpdk

- .mk/swagger.mk
- Makefile
> makefile: re-add swagger target

- contrib/exporters/Makefile.conf
- scripts/ci/create-binaries.sh
> binaries: get rid of LFS, compress instead

- contrib/ansible/roles/skydive_dev/tasks/ci.yml
> ci: fix docker cross build

- contrib/exporters/allinone/allinone.yml.default
- contrib/exporters/allinone/main.go
- contrib/exporters/awsflowlogs/awsflowlogs.yml.default
- contrib/exporters/awsflowlogs/mod/transform.go
- contrib/exporters/core/Makefile
- contrib/exporters/core/mangle.go
- contrib/exporters/core/pipeline.go
- contrib/exporters/secadvisor/main.go
- contrib/exporters/secadvisor/mod/mangle_logstatus.go
- contrib/exporters/secadvisor/mod/mangle_logstatus_test.go
- contrib/exporters/secadvisor/mod/transform.go
- contrib/exporters/secadvisor/secadvisor.yml.default
*** WORK IN PROGRESS ***
@eranra - please review log status logic at  `contrib/exporters/awsflowlogs/mod/mangle_logstatus.go`
@KalmanMeth - please check if **mangle** phase can also service Accept/Reject?
> exporters: add log status

- scripts/ci/kolla/Vagrantfile
> ci: install libvirt-libs for kolla tests

- scripts/ci/run-cdd-overview-tests.sh
- tests/selenium.go
> Report log cdd

- tests/runc_test.go
- tests/tests.go
Newer version of runc switched to bolt to store labels so
we disable the test on labels for now
> tests: disable test on runc labels

- probe/ebpf/Dockerfile
- probe/ebpf/common.h
- probe/ebpf/defs.h
- probe/ebpf/flow-gre.c
- probe/ebpf/flow.c
- probe/ebpf/flow_network.c
> Fix ebpf u16.04

- contrib/exporters/secadvisor/mod/resolve_vm.go
- contrib/exporters/secadvisor/mod/transform.go
Per recommendation of @hunchback
> exporters: adding VM resolver

- statics/js/components/object-detail.js
> ui: fix metadata key order

- .mk/ebpf.mk
- ebpf/Makefile
- ebpf/tests/tests.go
- flow/probes/ebpf/ebpf.go
- scripts/ci/run-unit-tests.sh
skip skydive-cdd-overview-tests skip skydive-coverage skip skydive-devstack-tests skip skydive-helm-tests skip skydive-kolla-tests skip skydive-skydive-release skip skydive-create-binaries skip skydive-compile-tests skip skydive-functional-tests-backend-elasticsearch skip skydive-functional-tests-backend-orientdb skip skydive-go-fmt skip skydive-k8s-tests skip skydive-packaging-tests skip skydive-python-tests skip skydive-scale-tests skip skydive-selenium-tests run skydive-unit-tests skip skydive-ppc64le-tests run vagrant-tests skip skydive-functional-hw-tests
> ebpf : non regression tests

- statics/js/components/capture-form.js
> ui: fix raw packet option not displayed

- contrib/ansible/roles/skydive_common/tasks/package.yml
Add yum update_cache after install centos-release-opstools
Change PR https://github.com/skydive-project/skydive/pull/2090
> Disable upgrade all packages

- topology/probes/lldp/lldp.go
- topology/probes/lldp/rawsockaddr_signed_int.go
- topology/probes/lldp/rawsockaddr_unsigned_int.go
> Fixed an issue with lldp

- go.mod
> build: add replace for opencensus-proto

- contrib/python/api/setup.py
- contrib/python/api/skydive/wsshell.py
Fix disconnection before flush
> Fix python websocket add function

- contrib/ansible/roles/skydive_dev/tasks/centos.yml
- contrib/ansible/roles/skydive_dev/tasks/fedora.yml
- contrib/vagrant/Vagrantfile
- contrib/vagrant/playbook-es.yml
- contrib/vagrant/requirements.yml
skip go-fmt
skip functional-hw-tests 
skip k8s-tests
> vagrant: do not require openstack plugin

- contrib/ansible/ansible.cfg
For a better CLI experience. For ofter testing ignoring ssh key
> Create ansible.cfg. For a better CLI experience. For ofter testing ignoring ssh key

- devstack/plugin.sh
- scripts/ci/devstack/run-devstack.sh
- scripts/ci/devstack/run-openstack-tests.sh
> devstack plugin: update the go version

- statics/workflows/flow-matrix.yaml
- tests/workflow_test.go
skip go-fmt
skip k8s-tests
pattern=.*Workflow
> Fix flow matrix

- flow/probes/ebpf/ebpf.go
1) Delete prevKey to optimize NextKey functionality. 
This lower the cpu to fifth of whet it cost to perform a kernel map iteration before the change.
2) Add sleep to avoid busy loop.
If there is no traffic on the interface then the condition in line 151 (old) to check sns will cause a busy loop and raise the cpu to 100%
> flow: High CPU in EBPF

- go.mod
> Use pseudo version go graffiti import

- topology/probes/netlink/netlink.go
> netlink: use transaction for FDB and Neighbors

- topology/probes/ovsdb/ovsdb.go
> ovs: do not confuse netlink interface with an OVS port

- config/config.go
- config/tls.go
- contrib/python/api/setup.py
- contrib/python/api/skydive/alerts.py
- contrib/python/api/skydive/auth.py
- contrib/python/api/skydive/captures.py
- contrib/python/api/skydive/graph.py
- contrib/python/api/skydive/packet_injector.py
- contrib/python/api/skydive/rest/client.py
- contrib/python/api/skydive/rules.py
- contrib/python/api/skydive/tls.py
- contrib/python/api/skydive/websocket/client.py
- contrib/python/api/skydive/wsshell.py
- contrib/python/api/tests/tests.py
- graffiti/tls/tls.go
- scripts/ci/run-python-tests.sh
- statics/js/app.js
> Add SSL support in Python client

- analyzer/storage.go
- config/config.go
- etc/skydive.yml.default
- graffiti/storage/elasticsearch/client.go
- tests/docker_test.go
- tests/elasticsearch_test.go
- topology/probes/lxd/lxd.go
> Limit Elasticsearch indices

- contrib/openshift/README.md
- contrib/openshift/deploy_skydive_ocp.sh
- contrib/openshift/skydive-template.yaml
Adding automatic deploy script
> Extend ocp deploy 

- contrib/openshift/README.md
- contrib/openshift/deploy_skydive_ocp.sh
- contrib/openshift/skydive-flow-exporter-template.yaml
- contrib/openshift/skydive-template.yaml
- Add pod with (1) flow_exporter and (2) minio (3) mc (mino command line) to create a bucket and tail new log files
- Add Skydive analyzer startup capture on host device interfaces
> add support for flow export

- .mk/static.mk
> User osusergo build tag for static builds

- .mk/proto.mk
- flow/flow.pb.go
- flow/layers/dhcpv4.pb.go
- flow/layers/dns.pb.go
- flow/layers/vrrpv2.pb.go
- go.mod
- graffiti/filters/filters.pb.go
- graffiti/go.mod
- graffiti/websocket/structmessage.pb.go
To address CVE-2021-3121
(https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3121)
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
> go.mod: Update to protobuf v1.3.2

- .mk/ui.mk
> ui: do not use pushd bashism

- js/package-lock.json
- js/package.json
- statics/ui/js/bundle.js
> js: add dependency on graffiti-js

- graffiti/api/server/edge.go
> api: create edge with the 'api' service type

- analyzer/server.go
- gremlin/traversal/ascendants.go
- gremlin/traversal/token.go
- validator/validator.go
The reserve side of Descendants step.
> Add Ascendants step

- scripts/ci/ovnkube-setup.sh
- tests/k8s/deployment.yaml
- tests/k8s_test.go
> Fix k8s tests to pass on kind

- graffiti/graph/graph.go
- graffiti/graph/graph_test.go
The goroutine consuming g.eventChan channel could get blocked if a
linker generate more than maxEvents events.
Fix this problem discarding events when the channel is full.
Return an error if this point is reached.
Increase the number of maxEvents to reduce the probability of event
discard.
> Fix event handler filling channel and being blocked

- graffiti/storage/elasticsearch/client.go
Skydive configured with ElasticSearch was deleting correct indices from
the alias. This was also causing an error while trying to create the
next archive index.
The error was considering all indices in the alias as incorrect.
Now, only indices with an old schema version are considered old.
If there is currently an index ponting to the alias, that one should be
considered as the valid one.
Fixes #2404
> ES: fix handling of aliases while starting

- scripts/ci/create-release.sh
skip go-fmt
skip k8s-tests
skip skydive-ovn-k8s-tests
> Enable OVN probe in released binary

- analyzer/server.go
- cmd/client/edgerule.go
- cmd/client/noderule.go
- cmd/seed/seed.go
- config/config.go
- config/websocket.go
- graffiti/clients/forwarder.go
- graffiti/clients/seed.go
- graffiti/clients/subscriber.go
- graffiti/cmd/client/client.go
- graffiti/cmd/client/edge.go
- graffiti/cmd/client/node.go
- graffiti/cmd/client/topology.go
- graffiti/endpoints/publisher_endpoint.go
- graffiti/endpoints/pubsub_endpoint.go
- graffiti/endpoints/replication_endpoint.go
- graffiti/endpoints/subscriber_endpoint.go
- graffiti/graph/metadata.go
- graffiti/hub/hub.go
- graffiti/hub/hub_test.go
- graffiti/hub/peering.go
- graffiti/hub/subscriber.go
- graffiti/pod/pod.go
- graffiti/seed/seed.go
- graffiti/websocket/client.go
- rbac/policy.csv
skip k8s-tests
skip skydive-ovn-k8s-tests
> Add cluster peering support

- go.mod
- go.sum
> Fix nimbess protobuf definitions
