skydive-project/skydive

flow/flow.go

Add layers path metric support, retreive layers path from the packet classifier.
Output example :
Ethernet.Dot1Q.IPv4.IGMP
Ethernet.IPv4.TCP
Ethernet.Dot1Q.IPv6.UDP.Payload
...

flow : add layers path metric

---

ovs/ovsdb_test.go
skydive.go

Set the new default to 256 bytes, aim to help the classifier on IPv6 and tunnels
trafic.

sFlow : new header size : 256 bytes

---

topology/netlink.go
topology/netlink_test.go
topology/ovs.go
topology/topology.go
topology/topology_test.go

Before this fix the netlink topo updater was erasing the
informations inserted by the ovs one.

Fix link overwriting between netlink and ovs

---

cmd/pcap2sflow-replay/pcap2sflow-replay.go
cmd/skydive_agent/skydive_agent.go
cmd/skydive_analyzer/skydive_analyzer.go
etc/skydive.ini.default
logging/logging.go

The newlogger read the configuration section [logging] to setup different
verbosity level. (default = INFO)
Valid level are : DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL
Configuration example:
[logging]
default = INFO
topology/probes = WARNING
Output example :
2016-02-02T23:37:08.538+11:00 quadnv.skydive_agent client.go:92 graph (*AsyncClient).connect > ERRO 007 Connection to the WebSocket server failed: dial tcp 127.0.0.1:8082: getsockopt: connection refused

New logger

---

topology/probes/netlink.go

The link can be added without the driver set first and then updated to a
bridge which leads to have twice the same node in the graph. With this
patch a bridge is always seen as a bridge.

Force driver to bridge when link type is bridge

---

README.md

I updated the config example to make agent en analyzer to start with that configuration file.
Explained that [openstack] is optional
Also explained the "listen" directive that binds by default on 127.0.0.1

Added [sflow] [ovs] [graph] sections in the conf example

---

topology/probes/netlink.go

We can be notified that a interface is created while it has just be
removed, then it is impossible to find it.

Change log from Error to Warning when netlink doesn't find intf

---

flow/statistics.go

Port should be a string represented by digit only.
Gopacket by default (via String()) return the service name as well like :
"80(http)"

[flow][statistics] fixup Port Number

---

flow/flow.go

Before this patch even the SFLow packet that was not of type Raw were
logged as critical. But this kind of packet are legitimate we just
don't support them for the moment, log them in debug.

Adapt log of SFlow packet parser, log as critical only non SFlow packets

---

flow/flow.go
storage/elasticsearch/elasticsearch.go

Appending the probepath to the id of ES we will have multiple entries
for the same flow depending where the packet has been captured so that
we can follow packets from point to point.

Append probepath for ES id so that we can follow flow

---

topology/probes/opencontrail.go

When vgw is used it has also type of vhost and it might be discovered
first in place of vhost0. In that case tap interfaces will not be linked
in the topology.

opencontrail: don't mix with vgw on devstack

---

flow/filters.go

Selecting node for period and requesting for
flow of them we could generated multiple time
the same filter. Use a map to generate one filter
per TID.
fixes: #276

flow: avoid adding twice same filter for node

---

analyzer/topology_server.go
api/topology.go
flow/storage/elasticsearch/elasticsearch.go
storage/elasticsearch/client.go
storage/orientdb/client.go
topology/graph/cachedbackend.go
topology/graph/elasticsearch.go
topology/graph/elasticsearch_test.go
topology/graph/graph.go
topology/graph/memory.go
topology/graph/memory_test.go
topology/graph/message_test.go
topology/graph/orientdb.go
topology/graph/orientdb_test.go
vendor/vendor.json

This patch aims to fix histo issue introducing a
Revision field and supporting multiple updates
at the same time.
For elasticsearch two updates will be merged.
For orientdb the Revsion field will be used
to ensure to get the right version of an element.
This patch ensures that the timestamp are the ones
set by agents.
This patch ensures also that edges deleted due to
node delete will have the same DeletedAt.

graph: replace timestamp mechanism by archive mechanism

---

topology/probes/netlink.go

Skydive does not show the relationship between Linux VLAN interfaces and
their parent interfaces. This is because the netlink topology probe
looks up the Vlan metadata field as a String, when adding the
child/parent relationship, but in fact Vlan is an integer. This change
fixes this issue by using the more generic GetField() function to look
up the Vlan metadata field.

Fix issue #304: orphaned VLAN interfaces

---

.gitignore

When launching virtual machines through vagrant, vagrant creates a hidden folder containing the state of those machines.
Signed-off-by: Christophe Vanlancker <christophe.vanlancker@inuits.eu>

Ignore .vagrant directory

---

Makefile
flow/storage/elasticsearch/elasticsearch.go
flow/storage/orientdb/orientdb.go
flow/table.go
flow/traversal/traversal.go

a flowState struct pointer is added to Flow generated struct
which can be used to keep internal flow status within the
flow table.
Metrics now makes use of this.

flow: introduce flowState and use json omit for raw packet

---

Makefile
cmd/cmd.go
cmd/completion.go
contrib/packaging/rpm/skydive.spec

skydive-bash-completion.sh is embedded inside skydive binary, via skydive
bash-completion command.

Build : move bash-completion out of build process

---

config/config.go
etc/skydive.yml.default
statics/js/components/graph-layout.js
topology/probes/ovs_of.go
topology/probes/ovs_of_test.go
topology/probes/ovsdb.go

The extension adds the possibility to view Openflow rules on 
OpenVSwitch bridges inside skydive. This is the **back-end part**
and will require changes to the front-end to be user-friendly.
The extension is enabled when the OVS probe is enabled and
ovsof.enabled is set to true.
Rules are displayed as nodes attached to an OpenVSwitch
bridge. Metadata include filters, actions, table and priority.
Without change to the front-end rules are displayed as
default nodes (interface).

Openflow rules on OpenVSwitch.

---

topology/probes/netlink.go
topology/probes/ovsdb.go
topology/topology.go

This occurs when an internal interface is pushed into
a namespace and the namespace is not seen by the netns
probe. In that case the netlink probe is not linking
the interface to the namespace. As the interface
can't be linked to the namespace this patch link it
to the ovs bridge.

ovsdb: link orphan ovs internal interface to bridge

---

topology/probes/ovs_of.go

As the name field is not not always filled
especially on deletion it is safer to use
uuid.
fixes: #368

ovsdb: use uuid instead name in bridge map

---

storage/elasticsearch/client.go
tests/neutron_test.go
topology/probes/neutron.go

We shouldn't use a map as metadata value or
we shouldn't modify it after commit since
a map is a pointer modifying it can be reported
to the datastore especially in case of bulk
operations.
This patch increases a bit the error chan.

neutron: do not reuse metadata map as value.

---

statics/js/components/graph-layout.js

Thix fixes an issue when we have a node
selected which is deleted. In that case
the next call the selectNode will raise
an exception.

ui: set selectedNode to null when deleted

---

statics/js/components/buttons.js

The callback registered on the document must be removed
as soon as it fires otherwise there is a long list of
callbacks that yields to a small memory leak and a real performance
problem.

ui: bugfix - Unregister buttons close callback

---

statics/js/components/graph-layout.js

This kind of interface are already linked to
the host through the chain of interfaces bridges,
moreover it makes the topology more readable.

ui: do not attach openstack vm tab to host

---

http/pool.go

Remove the half-useless eventHandlersLock lock
WARNING: DATA RACE
Write at 0x00c420160fb0 by goroutine 10:
github.com/skydive-project/skydive/http.(*WSClientPool).DisconnectAll()
/home/nplanel/devel/go/src/github.com/skydive-project/skydive/http/pool.go:116 +0x61
github.com/skydive-project/skydive/http.(*WSClientPool).Run()
/home/nplanel/devel/go/src/github.com/skydive-project/skydive/http/pool.go:213 +0x472
Previous read at 0x00c420160fb0 by goroutine 23:
github.com/skydive-project/skydive/http.(*WSClientPool).OnMessage()
/home/nplanel/devel/go/src/github.com/skydive-project/skydive/http/pool.go:76 +0x50
github.com/skydive-project/skydive/http.(*WSAsyncClient).run()
/home/nplanel/devel/go/src/github.com/skydive-project/skydive/http/wsclient.go:279 +0x59a

http : fix race in http client pool lock on evenHandlers

---

config/config.go
etc/skydive.yml.default
flow/flow.go
flow/flow.proto
flow/flow_test.go
flow/metrics.go
flow/storage/elasticsearch/elasticsearch.go
flow/storage/orientdb/orientdb.go
storage/elasticsearch/client.go

Added fixes after first round of reviews

flow: SYN/FIN detection

---

tests/openflow_test.go
tests/tests.go
topology/probes/ovs_of.go

Race between ovs-ofctl create and ovs-ofctl monitor when the bridge appears in ovsdb database
- added a functional test on openflow probe. It may exhibit the
problem
- added info logging (as for other probes) to make functional
tests log usable.
closes #370

openflow: bugfix - race with ovs-ofctl and functional tests.

---

tests/openflow_test.go
topology/probes/ovs_of.go
topology/probes/ovs_of_test.go

Rules can have the same filters (table, cookie, field filter)
but different priorities. They cannot be distinguished by ovs-ofctl monitor
and only dump-flows can discriminate them. The code was failing to
accomodate those rules by trying to be too smart both for adding and
deleting rules. The solution is to create a bucket for all rules with
same filter and associate the UUID obtained by forgetting about the priority.
Updating the content of the bucket is made by comparing the content
of the graph and the result of the query. Usually there is only one
rule in the bucket so performances are good.
closes #367

openflow: handles superimposed openflow rules

---

statics/css/skydive.css
statics/js/components/graph-layout.js
statics/js/components/topology.js

added a dedicated button for node to expand
and collapse all the child groups in the node group.

ui: expand all childs in a group

---

tests/openflow_test.go
topology/probes/ovs_of.go
topology/probes/ovsdb.go

When a bridge is closed, ovs-ofctl monitor receives the events that rules are removed but the probe fails to identify the priority of the rules and
does not remove them. So it is necessary to remove all rules from the graph.
closes #413

openflow: Openflow rules must be removed when bridge disapear

---

analyzer/server.go
api/user_metadata.go
cmd/client.go
cmd/client/user_metadata.go
tests/topology_test.go
topology/enhancers/user_metadata.go

User able to add and remove user metadata on node
ex-query: 1.skydive client user-metadata add --gremlin='g.v()' --key userkey --value userdata
2.skydive client user-metadata delete <UUID>

api: add/remove user metadata on node

---

devstack/plugin.sh

devstack master dies if it detects sudo in systemd unit commands
Also use KEYSTONE_AUTH_URI variable, available for a long time and works with new default keystone configuration

devstack: fix plugin for OSP Queens

---

topology/probes/neutron.go

IPs of Neutron don't have cidr, it is unfavorable for reading
We can add subnet cidr to the ips

Neutron: add subnet cidr to neutron ips

---

Makefile
contrib/snort/Makefile
contrib/snort/snortSkydive.go

Parse Snort message running with options "-A cmg -X" from a TCP socket
configured, for example snort.listen = 0.0.0.0:8888
The snort messages are saved in the flow, during the enhance step, thanks
to the flow pipeline. All snort messages are append to the flow.snort
field.

flow enhancers : add Snort alert messages

---

topology/probes/ovsdb.go

report ofport value and driver unknown when
interface is in ovsdb but not existing.

ovsdb: report ofport error

---

agent/agent.go
analyzer/flow_server.go
analyzer/server.go
http/pool.go
http/wsserver.go
tests/scale_test.go

Using the same AddClient implementation for WSPool and wsIncomerPool
leads to loose the original while add the listener. Then the on
disconnected callback is not the right one but always the one of
WSPool.
This causes to not disconnect the WebSocket Flow client.

websocket: add AddClient for wsIncomerPool to not loose the type

---

statics/js/components/node-selector.js

in capture select function should be disabled
after an error click

ui: node select should disable after error click

---

topology/graph/traversal/traversal.go
topology/graph/traversal/traversal_parser.go
topology/graph/traversal/traversal_test.go

Small change to add ability for SubGraph() to work on the output
of ShortestPathTo that returns list of lists
To check the functionality run:
g.V().Has("Name", "port1").ShortestPathTo(Metadata("Name", "port2"))
as a filter or find
Bug Fix: #556

Fix: Add ability to SubGraph to receive output of ShortestPath

---

statics/js/components/topology.js

now if we click the time icon with no data in date and time fields
it is showing Live in bottom of the screen.
the functionality is changed to show the current time

ui: bug fix for time icon click with no data

---

config/config.go
etc/skydive.yml.default
http/wsclient.go

Terminate a connection if ping failed and add parameter to set ping
delay. Now pne can increase pong timeout without increasing the
host_id conflict time as the connection lost will probably detected
while sending ping.

websocket: improve ping mechanism for better disconnection handling

---

Makefile

Can be tested by running:
$ export VERBOSE=true
$ make test.functionals.run
$ export VERBOSE=false
$ make test.functionals.run

tests: removed duplication in test.functionals.run

---

Makefile
api/capture.go
api/pcap.go
common/capture.go
contrib/python/api/setup.cfg
contrib/snort/snortSkydive.go
doc/content/getting-started/install.md
flow/allocator.go
flow/decoder.go
flow/flow.go
flow/flow_test.go
flow/pcap.go
flow/probes/dpdk.go
flow/probes/ebpf.go
flow/probes/gopacket.go
flow/probes/pcapsocket.go
flow/probes/probes.go
flow/table.go
packet_injector/inject_packet.go
probe/ebpf/Makefile
probe/ebpf/bpf.h
probe/ebpf/flow.c
probe/ebpf/flow.h
scripts/ci/ansible/deploy.yml
sflow/agent.go
statics/js/api.js
statics/js/components/capture-form.js
tests/flow_test.go
vendor/vendor.json

This new probe leverages eBPF and introduce
a flow table as a eBPF program.
eBPF program is embed as an asset of the
bindata.
This patch is a first step toward a more
complete version of the eBPF probe.
Change-Id: I4a74ceab22e1026bc686006f019e9abe686445c9

ebpf probe

---

doc/content/getting-started/install.md
probe/ebpf/Makefile

on Ubuntu 16.04 check no depredations by running:
```
$ sudo apt-get install -y clang llvm
$ cd probe/ebpf
$ make clean all
```
On Ubuntu 14.04 check that it compiles now by running:
```
$ sudo apt-get install -y clang llvm
$ sudo apt-get install -y bcc
$ cd probe/ebpf
$ make clean all
```

epbf: fix build on old distros (using bcc package)

---

statics/js/components/graph-layout.js

This fixes a bug introduce by
the commit cec365762dce258123dddb0220a250a7ba8adfd0

ui: fix default node/manager image

---

analyzer/server.go
config/config.go
etc/skydive.yml.default
statics/js/components/topology.js

Since making ssh from analyzer to agents might
be security violation in some cases, we add
configuration flag for administrators to enable/disble it

UI: configuration option to enable ssh to agents

---

topology/probes/neutron.go

When the Status of VM is "SHUTOFF", the tap node will disappear
we start skydive in this time, the qvb and qbr will not have neutron topology

Neutron：qvb and qbr don't have neutron topology

---

flow/traversal/traversal.go
statics/js/components/flow-table.js
statics/js/components/object-detail.js
statics/js/components/topology.js

It allows to detect whether a packet has reached
A or B. Otherwise they are always highlighted
even if the packet didn't not reach one endpoint.
Instead this add a link on the right side of the
ANddeTID, BNodeTID to highlights endpoints.

ui: highlight only capture node on flow mouse over

---

.gitignore
Makefile

The scope of these changes:
- cleanup - added `make skydive.cleanup` (and some other targets) to enable deleting artifacts created when building `make skydive`
- refactoring - mainly broke very long single lines within Makefile to multiline
- debug - added helper targets to build `make debug`, and run `make debug.agent` / `make debug.analyzer`
- go installation - added `make golang` to automate installation of Go

changes to build to include skydive cleanup and debug of skydive

---

agent/agent.go
analyzer/topology_replication_endpoint.go
http/pool.go
http/wsjson.go
http/wsmessage_test.go
http/wsserver.go
http/wsserver_test.go
tests/topology_test.go

Co-Authored-By: eranra@il.ibm.com
This is intended for debugging the correct creation/destruction of WS Pools, each pool is now assigned a new `name` field which is printed via logs.

http: added to debug info to WebSocket pools

---

common/service_test.go

Fedora resolve localhost as an IPv4 address and localhost6 as IPv6 address

test : Fedora resolve localhost as an IPv4 address

---

Makefile
common/types.go
common/types_test.go
config/config.go
etc/skydive.yml.default
statics/js/components/layout.js
topology/graph/graph.go
topology/probes/k8s/container.go
topology/probes/k8s/graph.go
topology/probes/k8s/k8s.go
topology/probes/k8s/networkpolicy.go
topology/probes/k8s/node.go
topology/probes/k8s/pod.go
vendor/vendor.json

This is a 2nd phase for the PR adding this capability for node discovery via the k8s probe itself (without relaying on the host agent).
To test just connect to a k8s landscape scape

K8s: add k8s container and node (host) discovery

---

config/config.go
etc/kube-config-empty.yml
etc/skydive.yml.default
topology/probes/k8s/client.go

If k8s.config_file (either defined or default value /etc/skydive/kubeconfig) does not exist then resolve k8s configuration as the `kubectl` does: first check `$KUBECONFIG`, next check `$HOME/.kube/config` finally resolve to empty definition (which works when running from within a k8s cluster).

k8s: fallback in case k8s.config_file is missing

---

config/config.go
etc/skydive.yml.default
http/auth.go
http/client.go
http/tls.go
http/wsclient.go

Several fixes affecting HTTP client (both REST and WS), which can be tested by using:
In skydive.yml
```
agent:
http:
debug: true
cookie: <value>
```
And then one can run the following commands:
```
skydive client status -c skydive.yml
skydive agent -c skydive.yml
```

HTTP: user defined "Cookie" and extended logging for client(s)

---

topology/probes/neutron.go

Execute "nova stop" to shut down a virtual machine, the tap node will disappear
execute "nova start" to power on virtual machine, tap node will rebuild
the new tap node doesn't have neutron topology

Neutron: tap nodes can not update automatically

---

analyzer/server.go
api/server/handler.go
api/server/packet_injector.go
api/types/types.go
cmd/client/packet_injector.go
packet_injector/client.go
packet_injector/inject_packet.go
packet_injector/server.go
statics/js/components/inject-form.js
tests/flow_test.go
tests/tests.go

added way to stop a long-running packet injector
cli-cmd:
skydive client inject-packet stop [flags]
Flags:
--src string    source node gremlin expression (mandatory)
--uuid string   UUID

pi: API to stop the injection

---

analyzer/topology_replication_endpoint.go
config/config.go
contrib/vagrant/Vagrantfile
etc/skydive.yml.default
http/auth.go
http/client.go
http/pool.go
http/wsclient.go
scripts/scale.sh
tests/tests.go

We discovered that our local analyzer was not able to connect with the remote analyzer (in the CogNETive demo landscape) if websocket compression was enabled, I have made this configurable (leaving current behavior as-is by setting default to 'true'). To test this you can override the default value by setting:
```
agent.http.websocket.enable_write_compression = false
```

http: WebSocket enable/disable of write compression

---

contrib/python/api/requirements.txt
contrib/python/api/setup.py

Fix the way the install_requires is written to allow correct parsing of
the requirements by python code.
The way it is currently written causes both trollius and asyncio to be
installed on python2, but asyncio is not compatible with that platform.
Install of skydive-client under python2 causes the following behavior:
==> devstack: Collecting skydive-client
==> devstack:   Downloading skydive-client-0.3.0.tar.gz
==> devstack: Collecting autobahn>=0.17.1 (from skydive-client)
==> devstack:   Downloading autobahn-17.10.1-py2.py3-none-any.whl (283kB)
==> devstack: Collecting trollius>=2.1; python_version < "3.0" (from skydive-client)
==> devstack:   Downloading trollius-2.1.tar.gz (276kB)
==> devstack: **Collecting asyncio>=3.4.3; python_version >= "3.0" (from skydive-client)**
==> devstack: …

Use different install_requires based on python version

---

contrib/python/api/requirements.txt
contrib/python/api/setup.py
contrib/python/api/skydive/websocket/client.py

Added login method to the python client to authenticate with the skydive
analyzer.
The authentication should be performed before the main loop is started.
The method returns a boolean specifying if the login succeeded. In case
it did, a cookie is kept and is sent with all the future requests.
Future work: detect cases in which the authentication is expired, and
raise a notification to the user or re-authenticate automatically.
Co-Authored-By: Omer Anson <oaanson@gmail.com>

Added login method to python client

---

logging/logging.go
logging/no_syslog.go
logging/syslog.go
vendor/vendor.json

Currently all logs sent to syslog have the critical severity.
With this patch depending on the level of the log the correct syslog
severity will be used.

logging: sync syslog severity with log level

---

flow/flow.go
flow/table.go
flow/table_test.go

We need to keep the flow last field aligned with a table
clock as the original timestamp can be seen by the table
after a long period. In this situation we have a flow
that is present in the flow table but that is
not sent to the analayzer since not seen as updated.

flow: keep a flow table clock to keep flow aligned

---

http/server.go
statics/js/app.js
statics/js/components/topology.js

- Open Skydive UI with custom view based on URL query string.
- Support for Multiple query keys,values
- Current support is for filter and highlight (gremlin expression)
Some examples:
http://localhost:8082/topology?filter=G.V().Has("Name", "AGGR1")
http://localhost:8082/topology?filter=G.V().Has("Name", "AGGR1")&highlight=G.V().Has("Name", Regex("AGGR1"))
http://localhost:8082/topology?filter=G.V().Has("Probe", Regex("fabric"))&highlight=G.V().Has("Name", Regex("AGGR1"))
Co-authored-by:    eranra <eranra@ERAN-TP>

ui: Add launch in context /topology?filter=<G>;hightlight=<G>

---

contrib/kubernetes/skydive.yaml

livenessProbe changes:
- analyzer now using /api/status
- elasticsearch *removed*
- agent *removed*
Can be tested using:
```
kubectl create -f skydive.yaml
kubectl get deployment
```

k8s: fixed livenessProbe (removed agent; analyzer using /api/status)

---

statics/js/api.js

Changes the name from UUIDpcap to UUID.pcap
closes #812

Fix filename for downloaded capture

---

statics/js/components/capture-list.js

if any error in capture get, list and delete
we are getting  not a function error for error notification

ui: fix 'not a function' error

---

Makefile

To check the feature:
```
$ cd /home/vagrant/go/src/github.com/skydive-projects/skydive
$ # this binds statics/index.html (and friends) into skydive
$ make                                                
$ # map assets to statics directory as follows
$ vim skydive.yml                                
...
ui:
assets: /home/vagrant/go/src/github.com/skydive-projects/skydive/statics
...
$ # change the file to *new*
$ vim statics/index.html                                
$ skydive analyzer -c skydive.yml 
$ # check content of index.html is *new*
$ curl localhost:8082                                     
```

'make debug' static assets are loaded from disk

---

api/client/gremlin.go
gremlin/query.go
gremlin/query_test.go
gremlin/value.go
tests/flow_test.go
tests/k8s_test.go
tests/tests.go

The effect of this change should be functionality natural in it I extended the gremlins query builder which is essence enabled to replace strings such as:
```
gremlin := fmt.Sprintf(`G.Has("Type", "%s")`, ty)
```
With functions - such as:
```
gremlin := g.G.Has("Type", ty)
```

tests: gremlin query builder 

---

statics/js/components/graph-layout.js
statics/js/components/topology.js

The expected result of launching with "expand" URL parameter is that on when layout is invalid - the following will happen:
- expands all levels
- performs a zoom fit (after some delay)

ui: add automatic expand via launching context /topology?expand

---

statics/js/components/flow-table.js
statics/js/components/graph-layout.js
statics/js/components/topology.js
tests/selenium_test.go

Have added option to toggle to latency on link labels.
How to use? for now this is exposed via launch context or URL parameter: `link_label_type=latency` if not specified then the default is `bandwidth` as was before.
The calculation of latency is by calculating the delta between `Math.abs(ANode.RTT-BNode.RTT)/1000`, with the underlying assumption that clocks are synchronized between nodes.
So as not to stress the system only visible nodes which has Capture enabled participate in latency calculation.
A possible test setup:
```
sudo ./scripts/simple.sh start 10.0.0.1/24 10.0.0.2/24
sudo ifconfig vm1-eth0 10.0.0.1
sudo ifconfig vm2-eth0 10.0.0.2
sudo ip netns exec vm1 tc qdisc add dev eth0 root netem delay 100ms
sudo tc qdisc add dev vm1-eth0 root netem delay 200ms
sudo tc qdisc add dev …
```

Ui link latency 

---

analyzer/flow_server.go
config/config.go
etc/skydive.yml.default

If we reach flow limit, all the flows from the channel are cleared
without saving the data and we send notification about it to the log.

flow: treat flows buffer overflow state

---

Makefile

Was useful to get this running on Power.

debian: support multiarchitecture using dpkg-architecture to discover path

---

scripts/simple.sh

fix handling when passing only one param to `start` or `ping` commands

scripts: fix simple.sh param checking

---

contrib/python/api/setup.cfg
contrib/python/api/skydive/rest/client.py

urllib.request is not supported on Python 2.7, modified to use urllib2
instead.

Fix python2 compatibility with urllib

---

statics/css/legend.css
statics/js/components/topology.js

Have added an option to hide via UI parameter the topology legend .. why? because when using very large Gremlin expressions the legend grows and conceals a large part of the topology pane.

ui: hide legend with URL param ?topology_legend_hide=true

---

statics/js/components/topology.js

if the time is converted to string don't
calculate bandwidth to avoid NaN error

ui: fix NaN error for node bandwidth

---

statics/js/components/graph-layout.js

use source node metrics to display bnadwidth
if no target node metrics

ui: improve bandwidth display

---

contrib/python/api/skydive/websocket/client.py

This is because there is no event_loop in threads by default, and in the
main thread it is created automatically.
This code resolves #929

When client is running in a thread, an exception is thrown

---

contrib/ansible/roles/skydive_common/tasks/main.yml

In order to have consistent host name
everywhere, otherwise we may have
fabric links not connected.

ansible: use ansible_hostname as host_id

---

contrib/python/api/setup.py
contrib/python/api/skydive/auth.py
contrib/python/api/skydive/websocket/client.py

Always use /login endpoint in order to use
a token instead of basic auth.

python: use login endpoint for authentication

---

analyzer/server.go
api/server/capture.go
api/server/packet_injector.go
api/server/server.go
cmd/client/capture.go
config/config.go
etc/skydive.yml.default
flow/ondemand/client/client.go
statics/js/api.js
statics/js/components/capture-form.js
statics/js/components/inject-form.js
statics/js/components/topology.js

added config variables to enable/disable
traffic capturing and packet injection.
With this configurable limitations Skydive can
be used in two modes: as a sniffering and as
a monitoring tool.
co-author: Sylvain Afchain <safchain@gmail.com>

flow: Added config vars to enable/disable capturing/injection

---

topology/probes/ovsdb/ovs_of.go

ExecCommandPipe emulated the behaviour of CommandContext that was
not available in go1.6.  Uses the maintained built-in version as the go minimum
version is 1.8.

oflow: use built-in CommandContext

---

http/auth.go
http/basic.go
http/keystone.go
http/server.go

This patch removes the support of the HTTP
part of our basic auth support as it causes
UI issue and authentification path inconsistency.
With this patch only the login endpoint using
the cookie returned as token is available.
Since this commit 81a691913310c2c019eb475bd64a760d8f6a6859
the python library relies on login and cookie.

auth: get ride of http basic auth

---

config/config.go
etc/skydive.yml.default
topology/probes/ovsdb/ovs_of.go

By default, ovs-ofctl only use 1.0 protocol. In that configuration, setting registers is
considered as an OpenFlow extension and the syntax is hard to read.
We introduce a configuration switch and set it to a reasonnable default.
Closes #973

oflow: Nice formatting of actions in rules using OpenFlow1.3

---

config/config.go
etc/skydive.yml.default
topology/probes/k8s/container.go
topology/probes/k8s/namespace.go
topology/probes/k8s/networkpolicy.go
topology/probes/k8s/node.go
topology/probes/k8s/pod.go
topology/probes/k8s/probe.go

to test try:
(1)
```
analyzer:
probes:
- k8s
k8s:
probes:
```
In this case we expect probes as listed in LOG to include: container, networkpolicy, namespace, networkpolicy, node, pod
(2)
Use some defaults
```
analyzer:
probes:
- k8s
k8s:
probes: 
node
```
In this case we expect LOG to indicate that only node probe of k8s is registered

k8s: generate defaults when k8s.probes is empty

---

config/config.go
contrib/snort/snortSkydive.go
etc/skydive.yml.default
flow/storage/elasticsearch/elasticsearch.go
flow/storage/orientdb/orientdb.go
flow/storage/storage.go
storage/elasticsearch/client.go
storage/elasticsearch/elasticsearch_test.go
topology/graph/elasticsearch.go
topology/graph/elasticsearch_test.go
topology/graph/graph.go
topology/graph/indexer.go
topology/graph/orientdb.go

the following change adds the infra changes needed for pointing topology and flow each to a different ElasticSearch database (the extra change need to support this is extending the `skydive.yml` `analyzer.storage` to support flow connection and point to this path during `NewConnConfig` call (for flow). 
This would enable extra isolation between the two in productive environments.
For now default behavior (in which both flow and topology take connection configuration from `storage.elasticsearch` remains).

es: support different elasticsearch connections per index

---

topology/probes/k8s/cluster.go

k8s: fix dumpcluster() func

---

tests/k8s/container.yaml
tests/k8s/pod.yaml
tests/k8s_test.go

k8s would fail sometimes as there was no mechanism to ensure skydive has seen the newly created k8s objects. A retry loop has been added to all k8s create object tests (10 retires with 1 second wait), eliminating this race and making the tests more stable.
If functional tests pass consistently again and again then this is indication the fix works as expected

k8s: fix flapping tests (especially pod, container)

---

agent/host.go

cpu index is starting from zero but the omitempty option not
allowing to display the first index which is zero

json: wrong json omitempty option in host cpu

---

Makefile

The `dpkg-architecuture` options and environment variables changed between 14.04 to 16.04 (see below), fixed the build command to support both version now.
Ubuntu 16.04 (http://manpages.ubuntu.com/manpages/xenial/man1/dpkg-architecture.1.html)
Ubuntu 14.04 (http://manpages.ubuntu.com/manpages/trusty/man1/dpkg-architecture.1.html)
To test just build on both target version.

build: fix static build for Ubuntu 14.04 (dpkg-dev 1.17.5)

---

statics/js/components/rule-detail.js

Some kind of actions are not breakable in smaller
chunks making the table overflow. A typical example
is userdata for controller that can be a large blob.
We replace the use of span with unicode zero length whitespaces to
create breakable points.

ui:  ensure openflow rule elements are split

---

common/common.go
topology/probes/opencontrail/opencontrail.go

One slow machines (such as test VMs), the delay (1.5 seconds) was
sometimes to small. This commit increases it to 8 seconds and adds the
retry function RetryExponential. The delay is doubled after each try:
the more failures we have, the more we wait for retries.

opencontrail: retry during 8 seconds to get the port from vrouter

---

Makefile
scripts/ci/opencontrail-tests.nix
scripts/ci/run-opencontrail-tests.sh
tests/opencontrail_test.go
tests/tests.go
topology/probes/opencontrail/opencontrail.go

The test uses a OpenContrail NixOS VM to run the OpenContrail Skydive
functional tests. This VM comes from the
github.com/nlewo/nixpkgs-contrail repository which uses it for its
packaging test suite.
To do:

tests: add opencontrail functional tests

---

tests/k8s/container.yaml
tests/k8s/daemonset.yaml
tests/k8s/deployment.yaml
tests/k8s/ingress.yaml
tests/k8s/job.yaml
tests/k8s/namespace.yaml
tests/k8s/networkpolicy.yaml
tests/k8s/pod.yaml
tests/k8s/replicaset.yaml
tests/k8s/service.yaml
tests/k8s/statefulset.yaml
tests/k8s_test.go

this changes introduces unique naming of objects each test creates, to ensure that when run in parallel one test does not conflict with another test.
To verify no degradations were introduced - we need to verify k8s functional passes

k8s: test use objects with unique prefix

---

scripts/ci/install-minikube.sh

this is added as a preparation of extending k8s NetworkPolicy supprt - for now all that need to be verified is that k8s tests still pass on the CI.

K8s minikube calico

---

contrib/packaging/rpm/skydive.spec
scripts/ci/build-copr.sh

skip skydive-go-fmt skip skydive-functional-tests-backend-elasticsearch skip skydive-functional-tests-backend-orientdb skip skydive-scale-tests skip skydive-selenium-tests skip skydive-unit-tests skip skydive-compile-tests skip skydive-k8s-tests

ci: fix copr build

---

Makefile

make vendor GIT repositories in vendor became corrupted (causing git errors), deleting these directories resolved the issue - `make fullclean` automates this.
in addition I have added some code cleanup/refactoring for top-level makefile.

Make s/cleanup/clean/ and other fixes

---

tests/k8s_test.go
topology/probes/k8s/node.go

Added new fields in node (k8s)  object such as:
- IP
- Hostname
- Cluster
- Labels
- Arch
- OS
Extended tests to cover.

k8s: enhance node metadata

---

statics/js/components/topology.js

When k8s probe is enabled, when clicking on k8s objects you will no see an extea panel with K8s detailed hairarchial data.

ui: place k8s metadata field in its' own panel

---

tests/k8s/pod.yaml
tests/k8s_test.go
topology/probes/k8s/cluster.go
topology/probes/k8s/graph.go
topology/probes/k8s/namespace.go
topology/probes/k8s/pod.go
topology/probes/k8s/probe.go

Eliminated entire-check retry mechanism (3 x 1sec) ; so now only relaying on a per gremlin-query retry (3 x 10sec). As having both retrys set would cause a multiplication of retries possibly having 9 retry attempt - with the new code only 3 retry attempts at max.

K8s tests retry

---

packet_injector/inject_packet.go
tests/flow_test.go
topology/graph/graph.go
topology/probes/netlink/netlink.go
topology/probes/ovsdb/ovsdb.go
topology/topology.go

This patch fixes the ownership link
overide mechanism that is involved
in ovsdb and netlink probes.

graph: fix ownership link override

---

scripts/ci/create-docker-image.sh

ci: do not use login when logging to docker hub

---

Makefile
tests/opencontrail_test.go
topology/probes/opencontrail/opencontrail.go
topology/probes/opencontrail/routing_table.go

This commit adds the Contrail routing table in the Contrail metadata
of a node. It relies on the Contrail binary `rt` to be notified on
route updates.

opencontrail: add routing table in Contrail metadatas

---

tests/k8s/networkpolicy1.yaml
tests/k8s/networkpolicy2.yaml
tests/k8s_test.go
topology/probes/k8s/graph.go
topology/probes/k8s/networkpolicy.go

Now netpol object is associated with both pods and namespaces:
* networkpolicy --association --> namespace
* networkpolicy --association --> pod
So that association does not conflict with ownership networkpolicy objects are owned by the cluster (not namespace).
The code includes two new test scenarios which verify association links have been created correctly.
NOTE: this PR depends on first merging: https://github.com/skydive-project/skydive/pull/1178
NOTE: this PR depends on first merging: https://github.com/skydive-project/skydive/pull/1182

k8s: extend netpol for namespaces

---

tests/k8s_test.go
tests/tests.go

add Test.preCleanup flag when set to `true` will run tearDown before running setup.
the k8s_tests make use of the flags, all other test have not changed (as flag is false by default).

Tests precleanup flag

---

js/package.json

npm WARN deprecated vue-json-schema@1.1.1: vue-json-schema has been moved to the FormSchema organization with the new name FormSchemaNative. Please use 'npm install @formschema/native' instead. More info: https://gitlab.com/formschema/native

js: use new repo @fromschema/native instead deprecated vue-json-schema

---

tests/k8s/persistentvolumeclaim.yaml

after running the previous test and checking minikube log:
```
minikube log 2>&1 | tee minikube.log
```
we would get the following warning (which has now been eliminated):
```
Jul 21 12:54:20 dev localkube[1252]: I0721 12:54:20.221934    1252 event.go:218] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"skydive-test-persistentvolumeclaim", UID:"2f2ef8db-8ce5-11e8-9484-5254001c08b7", APIVersion:"v1", ResourceVersion:"385976", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' storageclass.storage.k8s.io "manual" not found
```

tests: fix pvc test minikube log warning (of unrecognized storageclass)

---

tests/k8s_test.go
topology/probes/k8s/deployment.go
topology/probes/k8s/probe.go

Added new fields to deployment object, to tests run:
```
kubectl create -f tests/k8s/deployment.yaml
```

K8s: fix deployment metadata

---

tests/k8s/daemonset.yaml
tests/k8s_test.go
topology/probes/k8s/daemonset.go

Added metadata fields: Labels and Replica metrics which can be verified by:
```
kubectl create -f tests/k8s/daemonset.yaml
```

k8s: fix daemonset metadata

---

tests/opencontrail_test.go

tests: fix opencontrail compilation

---

CHANGELOG.md
contrib/ansible/roles/skydive_common/defaults/main.yml
contrib/packaging/rpm/skydive.spec
contrib/packaging/rpm/skydive.te.fedora
contrib/packaging/rpm/skydive.te.rhel

release: bump to 0.19

---

statics/css/graph-layout.css
statics/js/components/graph-layout.js

NOTE: depends on merging of https://github.com/skydive-project/skydive/pull/1163 when changes the RelationType form `association` to  `networkpolicy` w/o the current PR will have no noticeable effect.
This PR enhances k8s networkpolicy edges by addressing:
- coloring - light blue dashed line to indicate a "networkpolicy" edge
- arrowhead - indicating egress (pointing away) / ingress (pointing towards) and deny (red) / allow (green)
To test this PR setup k8s in configuration:
```
analyzer:
probes:
- k8s
```
And then create the various policies and check UI:
```
kubectl create -f tests/k8s/networkpolicy-ingress-allow.yaml
kubectl create -f tests/k8s/networkpolicy-egress-allow.yaml
kubectl create -f tests/k8s/networkpolicy-ingress-deny.yaml
kubectl create -f …
```

K8s: netpol arrowheads

---

common/types.go
tests/k8s_test.go
topology/probes/k8s/persistentvolume.go
topology/probes/k8s/persistentvolumeclaim.go

Enriched `persistentvolume` and `persistentvolumeclaim` objects with metadata

k8s: add metadata to pv and pvc objects

---

tests/k8s/service-pod.yaml
tests/k8s_test.go
topology/probes/k8s/graph.go
topology/probes/k8s/service.go

create links between `service` to `pod`, can be tested running:
```
kubectl create -f tests/k8s/service-pod.yaml
```
*NOTE*: depends on https://github.com/skydive-project/skydive/pull/1241

K8s service links

---

contrib/ansible/roles/skydive_dev/tasks/main.yml

We need iptables 1.6.1 as when using iptables 1.6.2 then minikube 0.25.2 fails (it has an issue with parameters passed to iptables-restore).
You can test this fix by creating a new devmode:
```
export PREPARE_BOX=true
vagrant up
vagrant ssh
vagrant@dev $ iptables -v
```
Note that after accepting this PR you need to build a new skydive/skydive-dev image as the current skydive-dev image has iptables 1.6.2 bundled into it.

devmode: explicitly install iptables 1.6.1

---

tests/k8s/networkpolicy-ingress-allow-namespace.yaml
tests/k8s/networkpolicy-ingress-allow-pod.yaml
tests/k8s_test.go
topology/probes/k8s/networkpolicy.go

You can test the new code using:
```
kubectl create -f tests/k8s/networkpolicy-ingress-allow-namespace.yaml
```

k8s: netpol support namespace <--> namespace(s) policy

---

statics/js/components/graph-layout.js

you can use:
```
kubectl create -f tests/k8s/networkpolicy-ingress-deny.yaml
```
the `deny` will be represented as a cross (X)

ui: k8s netpol deny uses an X

---

tests/k8s/networkpolicy-ingress-allow-ports.yaml
tests/k8s_test.go
topology/probes/k8s/networkpolicy.go

This PR adds the metadata field "Ports" to the links connecting networkpolicy to pod objects. Current implementation still has some limitations (as expressed by TODO within the patch)
To create a scenario which creates Ports: `:80` on edges run:
```
kubectl create -f tests/k8s/networkpolicy-ingress-allow-ports.yaml
```
NOTE: this PR depends on https://github.com/skydive-project/skydive/pull/1255

K8s netpol ports

---

contrib/dev/Vagrantfile

To test that there is not degradation run:
```
export PREPARE_BOX=true
vagrant up
```
Next run:
```
export HOSTNAME=dev2
export PRIVATE_IP=192.168.10.11
export PREPARE_BOX=true
vagrant up
```

devmode: make HOSTNAME and PRIVATE_IP configurable

---

analyzer/server.go
api/server/edgerule.go
api/server/noderule.go
api/types/types.go
cmd/client/client.go
cmd/client/edgerule.go
cmd/client/noderule.go
rbac/policy.csv
topology/enhancers/topology_manager.go
topology/enhancers/user_metadata.go
topology/graph/graph.go

sample command to create a fabric node:
```
skydive client node create --name="node1" --type="fabric" --query="create:" --metadata="fd=sdf"
skydive client node create --name="node2" --type="fabric" --query="create:" --metadata="fds=sdf"
skydive client edge create --src="g.v().has('Name', 'node1')" --dst="g.v().has('Name', 'node2')" --realtiontype="both"
skydive client edge create --src="g.v().has('Name', 'lo', 'State', 'UP')" --dst="g.v().has('Name', 'node1')" --realtiontype="layer2"
```

topology: add node/edge apis

---

scripts/ci/cleanup.sh

ci: restart libvirtd after cleanup

---

scripts/ci/install-istio.sh

This PR includes an install script which is the first step towards supporting istio environment on a kubernetes platform.
for testing, run the following commands from the path `scripts/ci/`:
./install-istio.sh install
./install-istio.sh start
./install-istio.sh stop
./install-istio.sh uninstall
./install-istio.sh status

istio: add install script

---

tests/k8s_test.go
topology/probes/k8s/pod.go

The first change extends the test so that it will check the validity of all the edges of k8s.  For checking, simply run the test.
The second change is aesthetic, fixing func name according to the real direction of the edge.

extending k8s hello-node test 

---

topology/probes/k8s/cluster.go

Insert endpoints to the cluster's node in k8s graph.
For testing, use ``` make debug.analyzer ```.

k8s: insert endpoints to cluster's graph entity

---

topology/probes/netlink/netlink.go

Some netlink messages can come with empty attributes
like MAC, MTU.

netlink: avoid update of empty attributes

---

scripts/ci/create-docker-image.sh

Running under dash generates the error:
scripts/ci/create-docker-image.sh: 20: scripts/ci/create-docker-image.sh: [[: not found
Replaced as the pattern /*/* doesn't match the D1 case is left unchanged:
$ D1=skydive/skydive
$ D2=registry.ng.bluemix.net:8080/skydive/skydive
$ echo ${D1%/*/*}
skydive/skydive
$ echo ${D2%/*/*}
registry.ng.bluemix.net:8080

docker/ci: create-docker-image.sh remove bashism

---

devstack/plugin.sh
scripts/ci/devstack/run-devstack.sh

Use the memory backend instead and save memory on the default
deployment. Most people is confused and believes that elasticsearch
is a mandatory component of a deployment, while it's not.
With this change I hope I can drive a wider usage in the openstack community.

Disable elasticsearch by default in devstack plugin

---

statics/js/components/rule-detail.js
topology/probes/ovsdb/ovs_of.go
topology/probes/ovsdb/ovs_of_test.go

Only rule addition and deletion were correctly handled.
This adds support for rule modification.
UUID do not include cookie as a rule with a distinct cookie but the same
filter will overwrite an existing rule.

openflow: fix openflow rule modification

---

devstack/plugin.sh

devstack: bump the go version as required

---

statics/js/components/rule-detail.js
tests/openflow_test.go
topology/probes/ovsdb/ovs_of.go
topology/probes/ovsdb/ovsdb.go

The Openflow probe did not display group tables because there was no obvious way to monitor them. Those two commits add support for groups. The hard part is in the probe where we use a mostly hidden functionality of OpenFlow 1.4. As one can expect group support will only work for OF1.5 enabled switch (we cannot safely enable it for 1.4 due to a bug in openvswitch corrected last week).

[openflow] Openflow group tables support

---

scripts/ci/create-docker-image.sh

skip skydive-opencontrail-tests

docker: fix remaining Id instead repo disgest

---

Makefile
scripts/ci/install-istio.sh
scripts/ci/install-minikube.sh
scripts/ci/jobs/jobs.yml
scripts/ci/run-functional-tests.sh
scripts/ci/run-istio-tests.sh
scripts/ci/run-k8s-tests.sh
scripts/ci/run-tests-utils.sh

the new istio test includes both k8s (ran on a system with istio) and istio tests. to check this fix you must add a CI hook enabling to write `run skydive-istio-tests` if successful it should replace the `run skydive-k8s-tests`

istio: now run-istio-tests executes both k8s and istio

---

Makefile
topology/probes/netlink/netlink.go
topology/probes/netlink/route.go

Check that a route or a nexthop is not already
present before adding it.

netlink: fix route and nexthop duplicated

---

statics/js/components/topology.js

ui: restore docker metadata

---

etc/skydive.yml.default
statics/js/components/topology.js

Added a ui independent parameter for enabling k8s artifacts such as filters (which may interfere with users  not using k8s). When you have the following setup:
- local-analyzer - collecting k8s and reporting upstream
- remote-analyzer - getting k8s info from local-analyzer and serving as webserver
```
local-analyzer (analyzer.topology.probes.k8s) ----> remote-analyzer (ui.k8s_enabled: true)
```
This parameter is disabled by default;  to enable it set:
```
ui.k8s_enabled: true
```

ui: add ui.k8s_enabled config parameter

---

statics/js/components/graph-layout.js

when we have a group with level one we are not able to expand that. this patch fixes that

ui: fix collapse/expand node by levels

---

topology/probes/neutron/neutron.go

Adds meta-information for peering in the case where the firwall
is provided directly by openvswitch with conntrack and not by the
hybrid iptable firewall.
Both the legacy and the new implementations are supported.
This is the bugfix part of #1410.

neutron: peering with ovs firewall

---

topology/probes/k8s/cache.go
topology/probes/k8s/container.go
topology/probes/k8s/k8s.go
topology/probes/k8s/pod.go

Fixed the bugs in containers implementation: 
- the container listened to graph events and used pod.K8s.Spec.Containers field to add/update/delete containers (rather than using the k8s runtime v1.Pod objects)
- the pod objects had the entire container metadata within them - making them needlessly large

K8s container operations based on k8s runtime events

---

common/tls.go
config/config.go
config/tls.go
etc/skydive.yml.default
scripts/ci/run-python-tests.sh
scripts/scale.sh

The implementation of TLS in Skydive is severely lacking and a little bit unorthodox. 
Here is an attempt at making the implementation a little more standard and easier to understand.
**Agent Does not use TLS unless CA Certificate and Keys are specified**
Previously, the logic for checking if the admin wanted TLS was to check whether the `analyzer:cert` was specified. This is counter-intuitive and bad security practice.
This MR changes this so that the logic is changed. 
**Concepts regarding certificates and services confusing**
Previously, the code used `analyzer:cert` for server certificates, and `agent:cert` for client certificates. This gets confusing, since when Skydive runs in "agent" mode, a server is set up. Why would it use the certificates from the Analyzer configuration for …

security: Improve TLS

---

Makefile
agent/probes.go
config/config.go
contrib/ansible/roles/skydive_dev/tasks/main.yml
contrib/docker/Dockerfile
contrib/docker/Dockerfile.compile
contrib/docker/Dockerfile.crosscompile
contrib/packaging/rpm/skydive.spec
devstack/plugin.sh
etc/skydive.yml.default
scripts/ci/create-binaries.sh
scripts/ci/create-release.sh
scripts/ci/run-compile-tests.sh
scripts/ci/run-tripleo-tests.sh
topology/graph/processor.go
topology/graph/processor_test.go
topology/probes/libvirt/libvirt.go
topology/probes/libvirt/no_libvirt.go
vendor/vendor.json

Libvirt probe dynamically polls the status of libvirt domains and their network
interfaces. For each new interface, it tries to enrich the coresponding tun
device with the name of the domain, the guest mac and the complete address of the
device on the guest pci bus.
The probe relies on libvirt-go the official go binding for libvirt that requires
the c libvirt library.
closes #1410

libvirt: initial version of libvirt probe

---

Makefile
scripts/ci/create-binaries.sh
scripts/ci/create-release.sh
scripts/ci/run-compile-tests.sh
scripts/ci/run-python-tests.sh
scripts/ci/run-tripleo-tests.sh

As libvirt can't be linked in static
User should not pass a special parameter in this case

Build : fix static and docker-image build

---

statics/css/skydive.css

Expand icon is not right aligned correctly when two consecutive
rows having expand icons.

Expand icon alignment issue

---

scripts/ci/run-unit-tests.sh

Bench test results are not used and rely on external
resource which is currenlty unavailable. Moreover
It would be better to pass the pcap file as an
argument and should be cached.

test: remove bench test as the result is not used

---

statics/js/components/rule-detail.js

The rule filtering functionality relies on a pre-filtering of the
graph. It breaked the display of port names in OpenFlow tables.
closes #1497

ui,openflow: quick fix of portnames

---

contrib/packaging/rpm/skydive.spec

packaging: bump rpm version to 0.21.0

---

statics/js/components/topology.js

The current namespace filters implementation is broken:
- they don't include the namespace (and cluster) nodes
- they should come as an addition to existing filters (e.g. k8s service + k8s namespace <X>) not a stand-alone filter
- they should be implemented as checkbox - such that one can choose several namespaces
Given all the above this feature has been removed and will be re-implemented correctly is the future.
To test this setup configuration to include  `ui.k8s_enabled=true` and verify that no `k8s namespace ...` filters exists anymore.

ui: remove k8s namespace filters

---

topology/probes/libvirt/libvirt.go

Libvirt Domain has multiple interfaces, but Libvirt Topology Probes
function getDomainInterfaces can only get one of them. Due to the
overlapping of the memory addresses of the loop variable `itf`.
issue: 1522

Support for multiple interfaces of libvirt domain

---

js/api.ts

in JS client not able to call 'Flows' step from 'V' Step

ui: not able to call 'Flows' from 'V' step

---

tests/bookinfo/bookinfo-networkpolicy-fix.yaml
tests/bookinfo/bookinfo-networkpolicy.yaml
tests/bookinfo/bookinfo.sh
tests/istio_test.go

add an independent driver script for the bookinfo sample - so it can be re-used by both k8s and istio testing, as well as being used for driving the bookinfo demo.
to run the script:
```
./tests/bookinfo/bookinfo.sh start
```

k8s: bookinfo driver script

---

contrib/python/api/setup.py
contrib/python/api/skydive/alerts.py
contrib/python/api/skydive/captures.py
contrib/python/api/skydive/rest/client.py
contrib/python/api/skydive/rules.py

This aims to provide the full support of the
capture API.

python: add more options to captures

---

topology/probes/k8s/graph.go

add default Labels field for all k8s/istio objects, with the following exceptions:
- cluster - does not have a labels field
- container - gets the labels field from the parent pod

k8s: add K8s.Labels field

---

analyzer/server.go
config/config.go
contrib/vagrant/Vagrantfile
scripts/ci/run-packaging-tests.sh
scripts/ci/run-vagrant-tests.sh
tests/tests.go

Use 'epel-7-x86_64' mock target to have Golang on CentOS

---

contrib/ansible/roles/skydive_common/tasks/package.yml

ansible: fix opstools repo installation

---

statics/css/graph-layout.css
statics/js/components/graph-layout.js
statics/js/components/topology.js

to tests view bookinfo sample in UI:
```
tests/bookinfo/bookinfo.sh start
```
to check:
1. expand default namespace
2. check color of all k8s associations in blue
3. check default arrowheads in black pointing from parent to child

ui: k8s arrowheads and default color

---

contrib/charts/templates/deployment-agents.yaml
contrib/docker/skydive.yml
contrib/kubernetes/skydive.yaml
contrib/openshift/skydive-template.yaml
etc/skydive.yml.default

This PR added runc mounts point in the kubernetes and openshift deployment, also configure using the agent configmap the relevant probes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/skydive-project/skydive/1556)

Added runc probe and mount points for cri-o

---

scripts/ci/install-minikube.sh

Add the option to setup minikube with calico (not enabled by default as this may several minutes until calico pods start running).
To tests run:
```
export WITH_CALICO=true
scripts/ci/install-minikube.sh install
scripts/ci/install-minikube.sh stop
scripts/ci/install-minikube.sh start
```
To test status run:
```
watch kubectl get pods --all-namespace
````
On my system (with my slow Internet) the system stabilized after 8 minutes:
```
[vagrant@dev ci]$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-54968cbc6c-jk5ld   1/1       Running   0          14m
kube-system   calico-node-d6x5n                          2/2       Running   0          14m
kube-system …
```

minikube: enable installing calico (WITH_CALICO=true)

---

flow/flow.go
flow/flow.proto
flow/table.go

Per @eranra suggestion, we suggest to add the  following fields to the Flow struct:
1. `Status` - will be one of {started, updated, ended}. (`started` for the first time a flow is reported, `ended` for the last time it is reported (expired or otherwise detected as ended by TCP flags), and `updated` otherwise).
2. `FinishType` for the reason the flow has ended (will be omitempty for cases where flow has not yet ended). Possible values are currently timeout, tcp_rst, tcp_fin. This can be extended to other types.
3. `ReportCounter` counts the number of times a flow has been reported.
I have not yet wrote any unit testing.
Would first like to get your opinion on this: @lebauce @nplanel 
Thanks!

Add Flow life cycle fields

---

statics/js/components/topology.js

when running with `ui.k8s_enabled: true` you should now see a new filter `k8s none` which shows all that is not k8s.

ui: add the 'k8s none' filter

---

tests/bookinfo/bookinfo-ibmcloud-image-policy.yaml
tests/bookinfo/bookinfo.sh

This was tested on IBMCloud here is the output:
```
$ ./bookinfo.sh start
export NAMESPACE=bookinfo
export WITH_ISTIO=false
export WITH_NETPOL=true
export WITH_IBMCLOUD=true
export SRVNAME=productpage
Error from server (AlreadyExists): namespaces "bookinfo" already exists
imagepolicy.securityenforcement.admission.cloud.ibm.com/ibmcloud-image-policy created
service/details unchanged
deployment.extensions/details-v1 unchanged
service/ratings unchanged
deployment.extensions/ratings-v1 unchanged
service/reviews unchanged
deployment.extensions/reviews-v1 unchanged
deployment.extensions/reviews-v2 unchanged
deployment.extensions/reviews-v3 unchanged
service/productpage unchanged
deployment.extensions/productpage-v1 unchanged
ingress.extensions/gateway unchanged …
```

bookinfo: add support for ibmcloud

---

topology/probes/istio/istio.go
topology/probes/k8s/k8s.go
topology/probes/k8s/probe.go

Now individual links can be disabled (as there is no why via Gremlin to do this) and this is required in various demo/productive scenarios.
To test you can disable the node2pod links by using:
```
analyzer:
topology:
k8s:
linkers:
- container2docker
- pod2container
- host2node
#- node2pod
- ingress2service
- networkpolicy2pod
- service2pod
```

k8s/istio: small refactor to linkers initialization code

---

vendor/vendor.json

Ethtool has sloved a bug:https://github.com/safchain/ethtool/pull/22/commits.
We'd better upgrade ethtoo vendor to newest.

vendor: upgrade ethtool to newest

---

devstack/plugin.sh
scripts/ci/devstack/Vagrantfile
scripts/ci/jobs/jobs.yml

tests: use fedora 29 for devstack

---

flow/probes/ebpf.go

In this commit we address the performance issue of agents using eBPF. We have come to realize that this mode of operation results in a very high CPU usage and we were able to attribute this phenomenon to the huge flow table that is kept in the memory and accessed using system calls which is a very expensive operation that slows down the system and results in the agents becoming stuck in the loop of trying to retrieve entries from the flow table. Hence, we suggest a fix in which we remove each entry after it has been read from the flow table and this way we are able to reduce the size of the table significantly eliminating the need to iterate over entries representing flows that had not been updated since we last encountered them.
In a future commit, we intend to address another serious …

fixed performance of agents

---

contrib/ansible/library/skydive_edge_list.py
contrib/ansible/library/skydive_node_list.py

Set the encoding to utf-8 in python files with utf8
characters (for python2).

bug: encoding of  python scripts

---

Makefile

Also cleans the generated.proto file. Not doing so gives weird
behaviour when switching to old  branches.

Build: clean generated file

---

scripts/ci/cleanup.sh

ci: clean docker volumes and vagrant cache

---

statics/js/components/edgerule-form.js
tests/topology_test.go
topology/enhancers/topology_manager.go

now edge-rule allows only ownership and layer2 in
relation type. now allowing all.
removed 'both' type.

topologyrule: Allow all the relation type

---

contrib/openshift/README.md
contrib/openshift/skydive-template.yaml

Hi folks,
after deploying & playing  with Skydive on OpenShift Container Platform and ran into Issue #1391 here some improvements for skydive on OpenShift:
- Change installation process to use git URL's instead of files. You don't have to clone the repo for an installation.
- OpenShift provides per default SSL encryption, so change the route from HTTP to HTTPS
- Add k8s analyser probe - inspired from pull request #1419 with some cleanups
- Cleanup Skydive configuration, idea is use only environment variables on one place for analyser and agent.
- Removed the configmap, from my point of view config map make only sense if you share the same configurations to many other objects, with skydive that is not the case. Analyser and agent has it own config map.
- Additional for the agend …

Update OpenShift Template - various changes

---

statics/js/components/topology.js

In the case that:
```
analyzer:
topology:
probes:
- k8s
```
no need to set:
```
ui:
k8s_enabled: true
```
as k8s filters  are enabled implicitly

ui: enable k8s filters implicitly

---

cmd/allinone/allinone.go
contrib/python/api/tests/tests.py
scripts/ci/run-python-tests.sh
scripts/scale.sh

tests: use allinone mode for python tests

---

contrib/objectstore/main.go
contrib/objectstore/skydive-objectstore.yml.default
contrib/objectstore/subscriber/flowtransformer/custom1/custom1.go
contrib/objectstore/subscriber/flowtransformer/flowtransformer.go
contrib/objectstore/subscriber/objectstore.go

This PR allows the object store flow subscriber to use a custom marshaller to transform the stored flows.
It includes one marshaller at the moment (named custom1) which is needed for a specific client using skydive.
This PR replaces the more generic (but perhaps less efficient) PR #1620.
As suggested here:
https://github.com/skydive-project/skydive/pull/1620#discussion_r250611550
@safchain @eranra

add objectstore marshaller

---

agent/host.go
etc/skydive.yml.default

This patch allows to specify files that will be read/watched
in order to fill the host node metadata with some of their values.

agent: add a way to report config file values as metadata

---

tests/istio/destinationrule-service.yaml
tests/istio/virtualservice-pod.yaml
tests/istio_test.go
topology/probes/istio/destinationrule.go
topology/probes/istio/istio.go

This PR creates link between destinationrule and service probes.
It also adds Istio test that checks this connection.

Istio: add link from destinationrule to service

---

Makefile
contrib/docker/Dockerfile
scripts/ci/create-docker-image.sh

moved all the related code (to building images) into `scripts/ci/create-docker-image.sh` and eliminated duplications between native to cross compilations.
@grooverdan - kindly check that the ppc64 still runs as expected (build appears to work).
@lebauce - note this change was made to support more easily features such as creating of snapshots etc.

ci: refactor create docker image

---

contrib/kubernetes/README.md
contrib/kubernetes/skydive.yaml
contrib/openshift/skydive-template.yaml

This PR fixes the contrib/k8s skydive template so that it is compatible with runC. To test do the following steps:
(1)
First create a runC container as explained here: https://blog.selectel.com/managing-containers-runc/
(2)
Next skydive as a k8s pod:
```
scripts/ci/install-minikube.sh
kubectl apply -f contrib/kubernetes/skydive.yaml
kubectl port-forward service/skydive-analyzer 8082:8082
```
(3)
Finally check in the WebUI that the `mycontainer` runC container exists.

Contrib k8s runc

---

etc/skydive.yml.default

The libvirt probe did not appear as a possibility in the etc/skydive.yaml file.
I added libvirt (commented) to the list of probes available.

added libvirt to list of probes in yaml file

---

contrib/kubernetes/skydive.yaml
topology/probes/runc/hosts.go
topology/probes/runc/runc.go
topology/probes/runc/runc_test.go

This PR enhances runC with information extracted from guest `/etc/hosts` in cases that this file is mapped from the host machine by runC, as is the case when using k8s 1.12.x (as is now the default in IBM Kubernetes Services). 
To test:
```
sed -e %skydive/skydive%aidans/skydive% contrib/kubernetes/skydive.yaml > skydive2.yaml
kubectl apply -f skydive2.yaml
kubectl port-forward service/skydive-analyzer 8082:8082
```
Now open runC container and check that you see in Metadata `Runc.Hosts` field.

Runc guest hosts

---

tests/istio/gateway-virtualservice.yaml
tests/istio_test.go
topology/probes/istio/gateway.go
topology/probes/istio/istio.go

This PR adds links between gateways and virtualservices.
The relevant tests are `TestBookInfoScenario` and `TestIstioGatewayVirtualServiceScenario`, which can be found at `tests/istio_test.go`.

Istio: add gateway-virtualservice link

---

flow/flow.go
flow/layers/layers.go

We add to extra fields for DNS flows to represent the query and the answer. The extra data we've added so far is not enough as it only displays the query and the answer, ignoring the authorities and other important fields. We would like to know what other fields you think are worth displaying.

added DNS fields

---

vendor/vendor.json

due to usage of cgo namespace _Ctype_... instead of C.
build error : 'identifier _Ctype_struct__xmlDoc may conflict with identifiers generated by cgo'

build: avoid go 1.12 build failed

---

config/config.go
etc/skydive.yml.default
flow/table.go
flow/table_test.go

We want to allow setting custom expire timeout for flow by their Application field.
For example, you may want to set DNS flows to timeout faster than the default 10 minutes.
I haven't yet tested this, but would like to get your feedback on the idea & implementation approach.
Thanks!

customize flow timeout by application

---

etc/skydive.yml.default

One the following are merged k8s is ready for productive use:
#1696 
#1690 
#1691

k8s: remove experimental note

---

tests/k8s_test.go
topology/probes/istio/destinationrule.go
topology/probes/istio/gateway.go
topology/probes/istio/virtualservice.go
topology/probes/k8s/cache.go
topology/probes/k8s/deployment.go
topology/probes/k8s/ingress.go
topology/probes/k8s/linker.go
topology/probes/k8s/pod.go
topology/probes/k8s/service.go
topology/probes/k8s/statefulset.go

this PR fixes a bug causing linker links to resources outside namespace to fail sometimes, specifically:
- storageclass --> namespace/pvc
- namespace/pvc --> pv
the fix removes automatic filtering by namespace in linker GetABLinks()/GetBALinks() and now in cases where namespace filtering is needed it the responsibility of implementer of XXXAreLinked() call back.
to test this works:
```
tests/k8s/storage.sh start
```
now check WebUI that links exists:
- [pod] default/task-pv-pod --> [pvc] default/task-pv-claim
- [sc] standard --> [pvc] default/task-pv-claim
- [sc] standard --> [pv] default/task-pv-volume

K8s: fix linker for non-namespace links

---

topology/probes/k8s/container.go

This PR fixes a bug in which when a pod is deleted its' child containers are not and remain orphaned (and flowing in space).
Test by running:
```
kubectl apply -f tests/k8s/pod.yaml
kubectl delete -f tests/k8s/pod.yaml
```
Verify in UI that not orphaned containers exist. (fixing the state if running this sequence on the current master).

k8s: delete orphaned containers

---

topology/probes/k8s/graph.go
topology/probes/k8s/persistentvolume.go
topology/probes/k8s/persistentvolumeclaim.go
topology/probes/k8s/pod.go

added for the sake of being able to debug cascading errors for k8s storage scenarios.
to test run:
```
tests/k8s/storage.sh stop
tests/k8s/storage.sh start
```
and obverse via WebUI how the following nodes are created initially:
- task-pv-pod - DOWN (red)
- task-pv-claim - DOWN (red)
- task-pv-volume - UP (standard) 
and eventually all settle on UP (standard)

k8s: UP/DOWN State for pod, pvc, pv resources

---

tests/istio/virtualservice-pod.yaml
topology/probes/istio/virtualservice.go
topology/probes/k8s/linker.go

This PR adds the ability to present non-trivial metadata about k8s/istio edges.
An example of it's usage is the case of virtualservice-pod edge: You can observe that the weight of the traffic sent to the pod is now showed in the edge's metadata.

k8s/istio: edge metadata mechanism

---

topology/probes/k8s/cache.go
topology/probes/k8s/service.go

this fixes the case in which a service (such as default/kubernetes) will point to all pods in case of an empty label selector (which is incorrect).
to check you can create a pod in the default namespace and make sure default/kubernetes service does **not** point to it.
to create the pod you can use:
```
kubectl apply -f tests/k8s/pod.yaml
```
NOTE: depends to https://github.com/skydive-project/skydive/pull/1690

K8s empty service links

---

contrib/kubernetes/skydive.yaml

To test:
```
kubectl apply -f contrib/kubernetes/skydive.yaml
kubectl port-forward service/skydive-analyzer 8082:8082
```

contrib/k8s: enable k8s probe with rbac

---

topology/probes/lldp/lldp.go
topology/probes/netlink/netlink.go
vendor/vendor.json

Some switches - such as Cisco Nexus - sends a different chassis ID
for each port, so you use SysName and MgmtAddress if present and
fallback to chassis ID otherwise.

lldp: prefer SysName and MgmtAddress to ChassisID for switch node id

---

cmd/client/topology.go
contrib/ansible/roles/skydive_agent/defaults/main.yml
contrib/ansible/roles/skydive_agent/tasks/container.yml
contrib/ansible/roles/skydive_agent/tasks/main.yml
contrib/ansible/roles/skydive_analyzer/defaults/main.yml
contrib/ansible/roles/skydive_analyzer/tasks/container.yml
contrib/ansible/roles/skydive_analyzer/tasks/main.yml
contrib/ansible/roles/skydive_common/defaults/main.yml
contrib/ansible/roles/skydive_common/tasks/container.yml
contrib/ansible/roles/skydive_common/templates/skydive.service.j2
contrib/ansible/roles/skydive_dev/tasks/docker-ce.yml
contrib/ansible/roles/skydive_dev/tasks/main.yml
contrib/ansible/roles/skydive_dev/tasks/virtualbox.yml
contrib/vagrant/Vagrantfile
scripts/ci/cleanup.sh
scripts/ci/jobs/jobs.yml
scripts/ci/run-vagrant-tests.sh
statics/workflows/flow-matrix.yaml
tests/tests.go
tests/workflow_test.go

Background:
libpod aka Podman is library for running OCI-based containers in Pods.
It is likely going to replace Docker in newer versions of RHEL systems,
which means Docker won't be supported in the future.
The CLI is supposed to work like it did with Docker (with some changes);
so this patch is pretty basic. It adds skydive_container_cli variable
(default to docker for backward compatibiility) and replace the
hardcoded "docker" commands by using this variable instead.
Some adjustments were made:
- podman doesn't need docker socket access.
- podman doesn't support --restart natively, we need a systemd service.
- podman doesn't require to have docker started.
Future iterations will be made to support proper SystemD/Podman
integration like it was done in TripleO for other containers: …

ansible: initial support for podman

---

tests/k8s/mysql-deployment.yaml
tests/k8s/wordpress-deployment.yaml
tests/k8s/wordpress.sh
tests/k8s_test.go

added a new k8s sample and test scenario - wordpress backed by mysql and pvc
you can check the PR by:
Open the WebUI and run:
```
tests/k8s/wordpress.sh start
tests/k8s/wordpress.sh status
tests/k8s/wordpress.sh stop
```

k8s/test: add wordpress sample

---

contrib/objectstore/subscriber/flowtransformer/custom1/custom1.go

The architects of security-advisor asked us to discard newly created flows (when they are first reported by the analyzer), unless they are expired/finished.
This PR implements their requested logic, as part of their `custom1` flow transformer.
@safchain I appreciate your help.

custom flow transformer - do not report new flows

---

flow/flow.go
flow/table.go
flow/table_test.go

Recently (in #1532), we started deleting flows immediately once we detect a TCP FIN/RST flags.
However, such flows can still see new packets, and thus we propose to add a "hold" duration to keep these flows in the flows table a bit longer.
Another change I made here is not report flows as "expired" if they are already reported as ended by other means (such as TCP FIN/RST).

hold ended flows

---

contrib/kubernetes/skydive.yaml

Added health checks to kubernetes skydive.yaml analyzer and agent containers.
```
kubectl apply -f contrib/kubernetes/skydive.yaml
kubectl port-forward service/skydive-analyzer 8082:8082
```

k8s: added health checks to skydive yaml

---

tests/docker_test.go
topology/probes/docker/docker.go

removed the leading back-slash in the `ContainerName` field:

docker: fix container name field

---

probe/ebpf/Makefile
scripts/ci/cleanup.sh

ebpf: do not use shell pipefail option

---

statics/js/components/graph-layout.js

This PR adds weight label on edges from virtualservice to pod, according to weight field in the edge metadata (if exists). 
For checking, look at the UI after executing the following command:
`kubectl create -f tests/istio/virtualservice-pod.yaml`

istio: add weight label on edges from virtualservice to pod

---

graffiti/graph/processor.go
tests/sriov_test.go
topology/probes/libvirt/libvirt.go
topology/probes/netlink/netlink.go
topology/probes/netlink/sriov.go

This is a very initial support for SRIOV with focus on the VM case (libvirt).
Principle:
* we use netlink to get initial information on the "virtual functions" (VF), the interface being the "physical function" (PF)
* we use ethtool to get the pci address of the PF,
* we explore /sys/bus/pci/devices/<address> to get the sriov offset and stride used to compute the pci address of the VF.
* libvirt will see the VF as a <hostdev> with driver vfio. The source address will be the pci address of the VF.
* We should be able to use peering to associate the mac address discovered in the VF to the mac address of the interface on the guest.

sriov and libvirt

---

contrib/objectstore/skydive-objectstore.yml.default
contrib/objectstore/subscriber/client.go
contrib/objectstore/subscriber/objectstore.go
vendor/vendor.json

The recently merged #1755 uses non-official repo.
I just found it there's an official one, so I'm switching to using it.
@safchain thanks in advance!

IBM OAuth - switch to using official ibm sdk repo

---

contrib/objectstore/subscriber/flowtransformer.go
contrib/objectstore/subscriber/objectstore.go
contrib/objectstore/subscriber/secadvisor.go

Another requirement of IBM's security advisor architects:
Do not store flows to object store which are neither tagged "ingress" or "egress".

filter flows by tag

---

Makefile

Based on: https://github.com/skydive-project/skydive/pull/1722
Removing libvirt from all static build targets.
To test run:
```
make test.functionals.static
make static
make compile.static
```

build: remove libvirt tag from static targets

---

topology/probes/k8s/container.go
topology/probes/k8s/graph.go
topology/probes/k8s/node.go

Provide cross links (which associate between k8s node to physical node) a meaningful RelationType:
- k8s.container --> docker
- k8s.node --> host
To test enable in skydive.yml:
```
analyzer:
topology:
probes:
- k8s
agent:
topology:
probes: 
- docker
```
And run allinone:
```
sudo $(which skydive) -c skydive.yml allinone 
```
Now verify that when pressing on cross links you see the correct RelationType

K8s cross links

---

topology/probes/istio/istio.go
topology/probes/istio/verifiers.go
topology/probes/istio/virtualservice.go
topology/probes/k8s/k8s.go
topology/probes/k8s/probe.go

This PR adds first sanity check for Istio configuration resources. In this check, if a virtualservice declares a gateway which doesn't exist, an error will appear in this virtualservice metadata.
As part of the implementation, k8s subprobes creation mechanism has been generalized.
To check the changes, one can create a virtualservice and the corresponding gateway with `kubect create -f tests/istio/gateway-virtualservice.yaml` and observe the "OK" state of the virtualservice. After that, one can delete the gateway by `kubectl delete gateways skydive-test-gateway-virtualservice` (refresh the page) and observe the "ERROR" state of the virtualservice.

istio: check existence of gateways declared by a virtualservice

---

tests/istio_test.go
topology/probes/istio/destinationrule.go

This PR adds a circuit breaker field to destinationrules metadata.

istio: add a circuit breaker field to destinationrules metadata

---

statics/js/components/graph-layout.js
tests/istio/virtualservice-pod.yaml
tests/istio_test.go
topology/probes/istio/virtualservice.go

This PR adds 'Protocol' field to virtualservice-pod edge metadata. 
The relevant tests, `TestIstioVirtualServicePodScenario` and `TestBookInfoScenario`, have been extended, such that now they check this property (the amount of traffic routed to each pod by the virtualservice, which was added to the edge metadata in a previous PR, is now being checked as well).

istio: add protocol field to virtualservice-pod edge metadata

---

tests/istio/destinationrule-serviceentry.yaml
tests/istio_test.go
topology/probes/istio/destinationrule.go
topology/probes/istio/istio.go

This PR adds links between serviceEntries and destinationRules.
Can be checked with `TestIstioDestinationRuleServiceEntryScenario`.

istio: add destinationrule-serviceentry links

---

Makefile
flow/flow.go
flow/flow.proto
flow/flow_test.go
flow/metrics.go
flow/storage/orientdb/orientdb.go
flow/table.go
gremlin/query.go
statics/js/components/flow-table.js
statics/js/components/graph-layout.js
tests/flow_test.go

This patch moves the RTT value to the Metric struct
in order to keep multiple version of it in the datastore.
The goal is to be able to get its value with only one
packet injection. For example create a long ICMP packet
injection with the same ID.
It is also improve the algorithm to rely on protocols
to get the 2 first packets. It avoid to calculate
the RTT in the middle of the flow.

flow: move RTT to Metric in order to keep track of it.

---

contrib/docker/Dockerfile.compile
contrib/docker/Dockerfile.crosscompile

docker: compile/crosscompile - bump gosu to 1.11

---

contrib/ansible/roles/skydive_dev/tasks/centos.yml
contrib/ansible/roles/skydive_dev/tasks/fedora.yml
contrib/ansible/roles/skydive_dev/tasks/lxd.yml
contrib/ansible/roles/skydive_dev/tasks/vpp.yml

ansible: do not install yum-plugin-copr on fedora

---

Makefile

To test install an updated delve
```
go get -u github.com/go-delve/delve/cmd/dlv
```
Then build Skydive:
```
make debug
```
Finally run (my patch fixes this stage):
```
make debug.analyzer
```

make: fix new delve execution against go1.9.x

---

contrib/docker/Dockerfile.compile
contrib/docker/Dockerfile.crosscompile

CI: bump protoc version 3.5.1 -> 3.7.1 and add native ppc64le/aarch64

---

Makefile
scripts/ci/jobs/jobs.yml
scripts/ci/run-istio-tests.sh

One commit enables to set TEST_PATTERN  for the test.functiomals.run target to be tested by:
```
make TEST_PATTERN=abc test.functionals.run 
```
The 2nd commit enables running tests under debugger (after installing delve) by:
```
make DEBUG=true test.functionals.run
```

Make test debug

---

statics/css/skydive.css
statics/js/components/panel.js
statics/js/components/topology.js

ui: display the node/edge ID in the metadata panel

---

Makefile
common/profile.go
scripts/ci/cleanup.sh
scripts/ci/jobs/jobs.yml
scripts/ci/run-tests-utils.sh
skydive_prof.go
tests/tests.go

ci: add mem profiling during functionals run

---

scripts/ci/install-minikube.sh

can be tested by:
```
$ scripts/ci/minikube-install.sh stop
$ scripts/ci/minikube-install.sh uninstall
$ scripts/ci/minikube-install.sh install
$ scripts/ci/minikube-install.sh start
```
then check:
```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-fb8b8dccf-tztxq            1/1     Running   0          7m9s
kube-system   coredns-fb8b8dccf-whhtj            1/1     Running   0          7m9s
kube-system   etcd-minikube                      1/1     Running   0          6m8s
kube-system   kube-addon-manager-minikube        1/1     Running   0          7m20s
kube-system   kube-apiserver-minikube            1/1     Running   0          6m24s
kube-system   kube-controller-manager-minikube   1/1 …
```

minikube: upgrade to v1.1.1

---

contrib/kubernetes/README.md
contrib/kubernetes/skydive.yaml

```
cd contrib/kubernetes
```
Change analyzer listening port from 8082 to 18082:
```
cat skydive.yaml | sed -e s/8082/18082/ | kubectl apply -f -
```
Change agent listening port from 8081 to 18081:
```
cat skydive.yaml | sed -e s/8081/18081/ | kubectl apply -f -
```
Change elasticsearch port from 9200 to 19200:
```
cat skydive.yaml | sed -e s/9200/19200/ | kubectl apply -f -
```
Change etcd port from 12379/12380 to 22379/22380:
```
cat skydive.yaml | sed -e s/12379/22379/ -e s/12380/22380/ | kubectl apply -f -
```
```
kubectl get pods                                 # check all RUNNING
kubectl get services                            # check correct ports
```

k8s: make all ports explicit (and configurable)

---

contrib/docker/Dockerfile.compile
contrib/docker/Dockerfile.crosscompile

build: fix docker image build, remove ppa

---

contrib/ansible/roles/skydive_dev/tasks/gimme.yml

ansible: bump golang to 1.10 for role skydive_dev

---

contrib/ansible/roles/skydive_analyzer/defaults/main.yml
contrib/ansible/roles/skydive_analyzer/tasks/keystone.yml

When deploying in a lab environment with self-signed certificates, playbook fails. This PR adds an option to disable certificate validation.

Add option to disable certificate validation

---

topology/probes/netns/netns.go

netns: fix unregistering of multiply registered paths

---

Makefile
contrib/pipelines/secadvisor/Makefile
contrib/pipelines/secadvisor/transform_test.go

To allow easier and safer changes in the future, add unit tests for the secadvisor pipeline's Transformer implementation.
```
$ go test -v
=== RUN   Test_Transform_basic_flow
--- PASS: Test_Transform_basic_flow (0.00s)
=== RUN   Test_Transform_UpdateCount_increses
--- PASS: Test_Transform_UpdateCount_increses (0.00s)
=== RUN   Test_Transform_Status_updates
--- PASS: Test_Transform_Status_updates (0.00s)
PASS
ok      github.com/skydive-project/skydive/contrib/pipelines/secadvisor 0.019s
```

secadvisor pipeline: Add unit tests

---

contrib/kubernetes/skydive.yaml

fixed minor issues in liveness/readiness, to validate no regression:
```
kubectl apply -f contrib/kubernetes/skydive.yaml
```

contrib/k8s: fix liveness and readiness

---

contrib/ansible/roles/skydive_agent/tasks/container.yml

ansible: add runc mount in container mode

---

probe/ebpf/Makefile

in order to avoid conflict with the DOCKER_IMAGE variable

build: use dedicated Makefile variable for the eBPF docker image

---

config/config.go
etc/skydive.yml.default
flow/probes/ebpf.go

Avoid to burst load the kernel every tick
Default flow polling rate : 16000 flow per second

ebpf : introduce a constant flow polling rate from the kernel

---

contrib/exporters/core/store_s3.go

Two small changes:
1. Serialize access to StoreFlows: we encountered panics (slice out of bounds) due to multiple goroutines modifying `s.flows` concurrently.
2. Appending incoming flows to current state (queue) instead of replacing current state.
Basically here we restore previous behaviour that was modified in commit cf3489644e051f048138ac504f2ce758978f19d6 .
@hunchback please review.
Note that there are ideas of how to improve this whole area of the code (in the future) - create a proper batching and queuing layers (maybe open source libraries already exist?) instead of slices and timers per tag.

exporters/core: Fixes for StoreS3: Serialize access, fix queueing

---

contrib/kubernetes/README.md
contrib/kubernetes/skydive.yaml

To test:
```
kubectl create namespace mynamespace
cat skydive.yaml | sed -e "s/namespace: default/namespace: mynamespace/" | kubectl delete -n mynamespace -f -
```

contrib/k8s: fix cluster role

---

gremlin/query_test.go
gremlin/value.go
tests/istio_test.go
tests/k8s_test.go

When constructing the Gremlin query string, double quotes were not
escaped, and therefore using a double quote char inside a query argument
would break the query.  This fix uses json.Marshal to quote a string, so
special chars like quote, newline, and tab will be backslash-quoted
inside the resulting Gremlin query string.
Moreover, quoting was done by passing the input as the format string to
fmt.Sprintf, which causes "format string injection" issues (these cannot
cause segfaults like in C, but still not very nice). It seems that this
functionality is not used at all, but also broke query arguments that
have the `%` char in them.
Note that this changes the public function signatures of `gremlin.Quote` and `gremlin.Regex` - it seems they are not used outside this package but please take …

gremlin: Properly escape query arguments

---

contrib/exporters/secadvisor/mod/resolve_cache.go
contrib/exporters/secadvisor/mod/resolve_fallback.go
contrib/exporters/secadvisor/mod/resolve_multi.go
contrib/exporters/secadvisor/mod/resolve_runc.go
contrib/exporters/secadvisor/mod/transform.go
contrib/exporters/secadvisor/mod/transform_test.go

the refactor of resolver is functional natural but will enable to easy support adding of additional resolution methods beyond runC such that we may have:
- runc (current secadvisor)
- docker (legacy secadvisor)
- k8s (future secadvisor)
- generic (which uses configuration) 
@KalmanMeth / @dubek / @eranra - kindly review

secadvisor: refactor resolver code

---

contrib/exporters/core/subscriber.go

contrib/exporters/core: Populate the X-Websocket-Namespace header
Following changes in the Skydive flow server to publish flows by capture
ID, the exporter subscription didn't receive any websocket messages it didn't
supply any namespace during connection (and therefore got a default
WildcardNamespace = `"*"`).  The flow server looks for subscribers
literally according to their requested namespace (and didn't take `"*"`
into account).
This fix makes the exporter websocket subscriber populate the
`X-Websocket-Namespace` HTTP header (on the websocket connection) with
the namespace `flow` or the namespace `flow/<CAPTURE_ID>` (if configured
to subscribe to a specific capture ID).
I think this was broken in commit da7e47bb785ec594b6ecfd38096c18aa40387f31 , but I'm actually fixing the client …

contrib/exporters/core: Populate the X-Websocket-Namespace header

---

contrib/exporters/Makefile.conf

More verbose test output is useful when examining CI logs.
The VERBOSE and TIMEOUT settings will be passed from the main Skydive makefile (when set).
To simplify, instead of specifically changing to the `mod` folder and running `go test` there, just run `go test` with the recursive pattern `./...` which fill find any `*_test.go` files and run them. This allows any exporter to choose its own folder structure.
@hunchback please review.

contrib/exporters: Run tests with verbose flag by default

---

contrib/exporters/secadvisor/mod/resolve_cache.go

Name resolving for IP addresses depend on the IP address and the TID in
which the flow was captured.  When caching the result, we now use both
IP and TID in the cache key (an IP address might appear in different places
in the cluster and refer to different containers/hosts/...).
@hunchback please review.

contrib/exporters/secadvisor: Fix IP's name caching

---

contrib/exporters/secadvisor/mod/resolve_docker.go
contrib/exporters/secadvisor/mod/transform.go

Add a resolver that finds the container name of a Docker container given
an IP address and nodeTID.
It is added in the MultiResolver *after* the Runc resolver; so if an IP can't be resolved in Runc metadata, we'll try to look it up as in Docker container node (see the code comment for the explanation of the Gremlin query).

contrib/exporters/secadvisor: Add Docker container resolver

---

contrib/python/api/skydive/captures.py
contrib/python/api/skydive/rest/client.py

python-api: improve python capture api

---

tests/selenium.go

ci: add retry to cdd selenium connection

---

graffiti/graph/traversal/traversal_test.go

Before this fix the tests printed the following log message (while passing):
=== RUN   TestBasicTraversal
--- PASS: TestBasicTraversal (0.00s)
traversal_test.go:204: Error in Sum() step: %!s(<nil>)
The fix correctly casts the result to int64 and fails if the `Sum()` function returns the wrong value.

graph/traversal: Fix Sum() unit test

---

common/types_test.go

In my attempts to understand how gremlin query like `G.V().Has('a.b.c.d', 'value')` accesses the value of `a.b.c.d`, and especially what happens if the node's metadata contains arrays (Kubernetes pod metadata, I'm looking at you), I ended up writing a unit test for `common.GetMapField` to validate my assumptions.
Ideally eventually we would add some documentation to http://skydive.network/documentation/api-gremlin , which has some examples of lookup of keys inside a nested map (like `G.V().Has('Docker.Labels.io.kubernetes.pod.namespace' ,'my-namespace').Descendants()`) but doesn't mention what happens if the metadata contains arrays.

common: Add unit test for GetMapField

---

analyzer/server.go
etc/skydive.yml.default

When using a startup capture, the config allowed setting the capture's
gremlin (which nodes should capture) and BPF filter string, but the
capture type was hard-coded to "pcap".
This change allows setting the type from the configuration: either
setting the `analyzer.startup.capture_type` key in the YAML config file or
by setting the `SKYDIVE_ANALYZER_STARTUP_CAPTURE_TYPE` environment
variable.
Possible values for `capture_type` are those that appear in `ProbeTypes`
(see `common/capture.go`); they are listed in a comment in the example
config file.
The default value for this config is `""`, which lets Skydive choose the capture type.
@eranra or @hunchback : please review.

analyzer: Allow setting startup capture type

---

api/server/packet_injector.go
api/types/types.go
api/types/types_easyjson.go
cmd/client/packet_injector.go
cmd/injector/standalone.go
contrib/python/api/setup.py
contrib/python/api/skydive/packet_injector.py
flow/ondemand/client/client.go
gremlin/traversal/nexthop_test.go
ondemand/client/client.go
packetinjector/client.go
packetinjector/forge.go
packetinjector/injector.go
packetinjector/injector_easyjson.go
packetinjector/injector_gendecoder.go
scripts/gendecoder/main.go
statics/js/components/inject-form.js
tests/flow_test.go
tests/tests.go
topology/nexthop.go

This aims to fix generation of unique packet ID when injecting from multiple nodes to one

Improve PI unique packet generation

---

contrib/exporters/core/pipeline.go

Before this fix we would always get empty flows input to the storer, because mangle() would always return an empty array per tag.
@hunchback please review.

exporters: Fix call to Mangle()

---

contrib/exporters/core/classify.go
contrib/exporters/core/compress.go
contrib/exporters/core/pipeline.go
contrib/exporters/core/store_buffered.go
contrib/exporters/core/store_direct.go
contrib/exporters/core/subscriber.go
contrib/exporters/core/write_s3.go
contrib/exporters/core/write_stdout.go

Fix most of the lint comments in `contrib/exporters/core`.
Here are the lint warnings that are still left (for this package) after these fixes:
```
subscriber.go:48:20: `pipeline` can be `github.com/skydive-project/skydive/websocket.SpeakerStructMessageHandler` (interfacer)
func NewSubscriber(pipeline *Pipeline, cfg *viper.Viper) (*websocket.StructSpeaker, error) {
^
pipeline.go:114:1: don't use `init` function (gochecknoinits)
func init() {
^
pipeline.go:85:2: `ManglerHandlers` is a global variable (gochecknoglobals)
ManglerHandlers     HandlersMap
^
pipeline.go:86:2: `TransformerHandlers` is a global variable (gochecknoglobals)
TransformerHandlers HandlersMap
^
pipeline.go:87:2: `ClassifierHandlers` is a global variable (gochecknoglobals)
ClassifierHandlers  HandlersMap
^ …
```

exporters/core: Fix lint warnings

---

contrib/exporters/secadvisor/mod/resolve_docker.go
contrib/exporters/secadvisor/mod/resolve_docker_test.go
contrib/exporters/secadvisor/mod/resolve_runc.go
contrib/exporters/secadvisor/mod/resolve_runc_test.go
contrib/exporters/secadvisor/mod/resolvers_test.go
contrib/exporters/secadvisor/mod/transform_test.go

This is an attempt to increase unit test coverage of the exporters functionality.
This PR adds tests for the two name resolvers: `resolveDocker` and `resolveRunc`. The tests use implement a local gremlin instance (see `resolvers_test.go`), whose topology graph is populated from a local JSON file. The resolver's queries are executed against this local instance (instead of being sent as HTTP request in the real resolver case).
In order not to commit large hard-to-understand topology files, I removed unnecessary info from the JSON topology files so that they include only the relevant nodes and links.
Following @hunchback 's advice, after we gain some experience with this local gremlin instance for testing here, it might be useful to extract it to the a Skydive-wide package (perhaps under …

exporters: Test gremlin resolvers using local topology files

---

contrib/helm/templates/deployment-agents.yaml
contrib/openshift/skydive-template.yaml

OpenShift seems to store state files about containers under `/var/lib/origin` and `/var/data/openshiftvolumes` . In order for the Skydive agent Runc probe to successfully extract container information on OpenShift, it should have access to these directories.
Without this we got the following errors in `parseHosts` (unfortunately in `DEBUG` level) at the beginning of the agent log when running in OpenShift 3.11:
```
2019-09-05T08:02:21.232Z        INFO    agent/agent.go:41 glob..func1   kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: Skydive Agent _2019-09-02T05:45:19 starting...
...
2019-09-05T08:02:21.251Z        ERROR   runc/runc.go:346 (*ProbeHandler).initializeFolder       kube-wdc04-crac1766060dcf4354816f6b171eae7a7b-w1.cloud.ibm: no such file or directory …
```

contrib/openshift, charts: Mount OpenShift dirs in agent pod

---

scripts/ci/create-docker-image.sh

Both Docker.compile and Docker.crosscompile don't use the `BASE`
build-arg at all.  The output log of the CI ([example](http://ci-logs.skydive.network/skydive-create-docker-image/builds/3/log)) shows this:
[Warning] One or more build-args [BASE] were not consumed
This patch removes this unused build-arg from the
`skydive-compile-build` image building (it is still used in the skydive
or snapshot images to allow setting `BASE` per architecture).

ci/create-docker-image.sh: Remove unused BASE build-arg

---

scripts/gendecoder/main.go

gendecoder: use pkg name instead of filename

---

scripts/ci/create-docker-image.sh

When running the skydive build (compile) inside the build container:
Instead of using `$GOPATH` from the host (which is something like
`/home/user/go`) as-is inside the builder container, use the proper
`$GOPATH` directory which is `/root/go`.

ci/create-docker-image: Fix GOPATH inside the build container

---

agent/topology_probes.go
analyzer/probes.go
config/config.go
go.mod
topology/probes/bess/bess.go

Berkley Extensible Software Switch (BESS) is a modular network data
plane. This patch adds topology support for BESS instances running on
different hosts through an agent probe. Adding metrics and
monitoring/tcpdump is still WIP and will be added in a follow up patch.
Signed-off-by: Tim Rozet <trozet@redhat.com>

Adds BESS topology probe

---

Makefile

Makefile: check for GO111MODULE before running go mod download

---

statics/js/components/capture-form.js

after choosing target type if change the capture type
to ovssflow or ovsnetflow raw packets limit not appear again

ui: fix raw packets limit display

---

contrib/packaging/rpm/skydive.spec

packaging: file skydive binary location for bash completion build

---

CHANGELOG.md
api/server/server.go
contrib/ansible/roles/skydive_common/defaults/main.yml
contrib/packaging/rpm/skydive.spec
contrib/packaging/rpm/skydive.te.fedora
contrib/packaging/rpm/skydive.te.rhel
scripts/ci/create-vagrant-boxes.sh

Bump to version 0.26.0

---

flow/ebpf.go

When building on arm64 the build fails due to invalid cast from golang
int to C.int.  Explicitly casting to C.int like so fixes the
build.

build: Fix build error due to implicit cast to C.int

---

topology/probes/k8s/deployment.go
topology/probes/k8s/k8s.go
topology/probes/k8s/replicaset.go

Original implementation connected Pods directly to Deployments, skipping ReplicaSets

Fix K8s probs links Deployment->ReplicaSet->Pods

---

etc/skydive.yml.default
topology/probes/k8s/cluster.go

When SkyDive runs as a K8s deployment it doesn't have `kubectl`
context, so the cluster name is always "cluster". This fix allows
to define cluster name explicitly.

Allow to set K8s cluster name from the config yaml file

---

contrib/helm/templates/deployment-agents.yaml

The agents daemon set requires extensive rights. To be able to deploy it in a cluster with a restrictive default pod security policy we need to have a service account associated with them. 
The pull request adds the skydive-service-account to the agents to be able to assign pod
security policies with a rolebinding - as it is already done for the analyzer.

Fix missing service account on agents

---

contrib/kubernetes/skydive.yaml

On the new kubernetes release some changes is needed like the name of the apiVersion and selector which is mandatory.

Change apiVersions and add selectors to fits new k8s release >=1.16

---

topology/probes/istio/istio.go
topology/probes/k8s/cache.go
topology/probes/k8s/cluster.go
topology/probes/k8s/graph.go
topology/probes/k8s/k8s.go
topology/probes/k8s/probe.go

When we have a combine view of several K8s clusters, currently we cannot separate objects from different clusters.
This PR adds the `ClusterName` metadata property to all K8s objects, so UI will be able to separate them.

Add ClusterName metadata to K8s objects

---

tests/blockdev_test.go
topology/probes/blockdev/blockdev.go

When the full path to a block device is used for the node name it can be difficult to read on a graph with many devices.
Also, update block metadata from "WWN" to "ID" since not all block devices have WWNs.

Change the blockdev node name to just the base name insead of full path

---

go.mod
websocket/server.go

Deadlock trace:
goroutine 103 [semacquire, 4 minutes]:
sync.runtime_SemacquireMutex(0xc00033cfac, 0x0)
/var/lib/jenkins/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:71 +0x3d
sync.(*RWMutex).RLock(0xc00033cfa0)
/var/lib/jenkins/.gimme/versions/go1.11.13.linux.amd64/src/sync/rwmutex.go:50 +0x99
github.com/skydive-project/skydive/websocket.(*Server).serveMessages(0xc000328a80, 0xcf46a0, 0xc000146700, 0xc00039e240)
/var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/websocket/server.go:83 +0x536
github.com/skydive-project/skydive/websocket.(*Server).serveMessages-fm(0xcf46a0, 0xc000146700, 0xc00039e240)
/var/lib/jenkins/workspace/skydive-unit-tests/src/github.com/skydive-project/skydive/websocket/server.go:206 +0x60 …

websocket: fix deadlock and remove duplicated mutex

---

topology/probes/k8s/cluster.go
topology/probes/k8s/graph.go

When skydive probes several K8s clusters, we have to separate their topology

add cluster separation

---

Makefile
api/server/no_packet_injector.go
api/server/packet_injector.go
api/server/packet_injector_common.go
packetinjector/no_server.go
packetinjector/server.go
packetinjector/server_common.go

Packet may be a security concern. When it is not needed it is
better to no have it available at all.
This patch adds a build flag "nopacketinject" to disable packet
injection if needed.

Add build flag to disable packet injection

---

contrib/python/api/skydive/rest/client.py

API server renders the Content-Type header based on the Accept header
(graffiti/api/server/topology.go#L120).
If the client does not specify that header, the response is not
unmarshaled and raise an exception tryinh to get values from a byte
string (instead of a python dict), in function from_object

Fix python client to get the correct content type

---

graffiti/graph/traversal/traversal.go

Query "G.At(0).V().As('x')" was crashing the analyzer because
a "assignment to entry in nil map".
GraphTraversal.as was not initializated after cloning the graph in the
"At/Context" step.
"As" step produced the panic while trying to assign a value to the
uninitializated map
Fixes #2230

Fix panic if gremlin query At() and As() were used

---

graffiti/schema/validator.go

Currently an error in the node/edge schema gives no clue to the user to
where is the error.
Append to that message the list of errors returned by the validator.
Eg.:
```
Invalid schema: [CreatedAt: Invalid type. Expected: integer, given: null UpdatedAt: Invalid type. Expected: integer, given: null (root): Must validate all the schemas (allOf)]
```
Could be improved to separate different messages

Return to the user the reason of the invalid schema

---

contrib/python/api/samples/fs-watcher.py
contrib/python/api/skydive/rest/client.py

Following the current implementation for noderule/edgerule in python and
node/edge create in the "skydive client".
Data validation is done by the server.
skip go-fmt
skip k8s-tests

Python: add create/list/delete for node and edge

---

contrib/python/api/skydive/rest/client.py

Time format for fields CreatedAt, UpdatedAt should be unix epoch
millisecond (epoch_millis in the elasticsearch template)

CreatedAt and UpdatedAt fields should me unix epoch millisecond

---

graffiti/service/address.go
graffiti/service/address_test.go

While using TLS, certs use to be valid for domain names, not for IPs.
Without this patch, communication between skydive itself is done using
the IP, failing if the cert does not contain the IP.

Do not convert hosts to IPs

---

topology/probes/k8s/daemonset.go
topology/probes/k8s/deployment.go
topology/probes/k8s/networkpolicy.go
topology/probes/k8s/replicaset.go
topology/probes/k8s/statefulset.go

Fixes #2169, #2251 and also complement the Helm Chart fix of skydive-project/skydive-helm/issues/2

Update k8s api compatibility

---

statics/js/components/rule-detail.js

Currently, expanding the Rule detail view on a OvS Bridge fails with:
```
vue.min-2.5.16.js:6 TypeError: Cannot read property 'map' of undefined
at textBucket (rule-detail.js:250)
at Array.map (<anonymous>)
at summarizeGroup (rule-detail.js:257)
at BridgeLayout.extract (rule-detail.js:404)
at BridgeLayout.compute (rule-detail.js:433)
at new BridgeLayout (rule-detail.js:376)
at o.layout (rule-detail.js:786)
at St.get (vue.min-2.5.16.js:6)
at St.evaluate (vue.min-2.5.16.js:6)
at o.layout (vue.min-2.5.16.js:6)
```
The fix is quite simple :)

ui: Fix typo in rule-detail parsing

---

contrib/kubernetes/skydive.yaml

Skydive is no longer compatible with Elasticseach 5.
Use latest stable version: 7.8
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>

contrib/kubernetes: bump elasticsearch version

---

tests/k8s_test.go

k8s: wait for k8s resources to be deleted in tests

---

topology/probes/ovn/ovn.go

Currently the event processing goroutine is created after
go-ovn.NewClient() is called. The go-ovn.Client constructor populates
the initial cache content, triggering callbacks that need processing.
If more than 50 callbacks are triggered (the size of the buffered
channel), we have a deadlock.
Fix that by creating the worker goroutine first
Fixes #2275 
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>

ovn-probe: Create worker goroutine before ovn Client

---

topology/probes/ovn/ovn.go

After #2288 was merged we ended up with a duplicated goroutine.
Remove it.

ovn: remove duplicated goroutine

---

analyzer/server.go
analyzer/storage.go
config/config.go
etc/skydive.yml.default
graffiti/go.mod
graffiti/storage/elasticsearch/client.go
scripts/ci/run-tests-utils.sh
tests/elasticsearch_test.go

Allow skydive to connect to Elasticsearch servers with TLS but invalid
certs.
For Elasticsearch clusters, be able to only define a single endpoint
creates a SPoF at start time. Allow to pass an array of endpoints.
This breaks the current config, which expect an string in the key
"host".
Now is an slice in the key "hosts".
Expose configuration for basic auth (previously supported with
http://user:password@...)
Add option 'disable_sniffing' to etc/skydive.yml.default, already
implemented.
Add option 'disable_healthcheck' to etc/skydive.yml.default.
Fix a typo in the error string when Elasticsearch version could not be
obtained.
Add olivere/elastic logging to skydive logger. Ease debuging problems
with Elasticsearch.

Elasticsearch: define several hosts and allow invalid certs

---

CHANGELOG.md
Makefile
contrib/ansible/roles/skydive_common/defaults/main.yml
contrib/packaging/rpm/skydive.spec
contrib/packaging/rpm/skydive.te.fedora
contrib/packaging/rpm/skydive.te.rhel
contrib/packaging/rpm/specfile-update-bundles
graffiti/api/server/server.go
scripts/ci/create-vagrant-boxes.sh

Bump to version 0.27.0

---

.gitignore
.mk/k8s.mk
README.md
contrib/charts/Makefile
contrib/charts/skydive-agent/Chart.yaml
contrib/charts/skydive-agent/Makefile
contrib/charts/skydive-agent/templates/_helpers.tpl
contrib/charts/skydive-agent/templates/daemonset.yaml
contrib/charts/skydive-agent/values.yaml
contrib/charts/skydive-analyzer/Chart.yaml
contrib/charts/skydive-analyzer/Makefile
contrib/charts/skydive-analyzer/templates/NOTES.txt
contrib/charts/skydive-analyzer/templates/_helpers.tpl
contrib/charts/skydive-analyzer/templates/clusterrolebinging.yaml
contrib/charts/skydive-analyzer/templates/deployment.yaml
contrib/charts/skydive-analyzer/templates/service.yaml
contrib/charts/skydive-analyzer/templates/serviceaccount.yaml
contrib/charts/skydive-analyzer/values.yaml
go.mod

in this PR I provide a:
- two independent charts skydive-analyzer and skydive-agent to enable more flexible deployments
- upgrade to helm3
note that I want to propose using the main repo `skydive` rather than auxiliary repos as this will provide for easier integration, faster development, and better CI coverage (later I would propose EOL of the `skydive-helm` and `skydive-operator`). some examples of other projects which use this approach:
- Fleet: https://github.com/rancher/fleet/tree/master/charts
- Istio: https://github.com/istio/istio/tree/master/manifests/charts/base
- cert-manager: https://github.com/jetstack/cert-manager/tree/master/deploy/charts/cert-manager
no CI tests currently - so attaching the status output
traverse to charts directory
```
cd charts
```
create a local test …

charts: helm v3 charts for agent and analyzer

---

config/config.go
etc/skydive.yml.default

Use etcd default value for maximum wal and snap files

---

contrib/charts/Makefile
contrib/charts/elasticsearch/Makefile
contrib/charts/kibana/Makefile
contrib/charts/skydive-analyzer/Makefile

this is an extention above skydive-analyzer helm to enable it to use an external elasticsearch (which is visualized by kibana)
to use this:
```
cd charts
make install
```
now access skydive browser at http://localhost:30000
and access kibana with browser at http://localhost:30030

Charts: added make command to run helm based elasticsearch/kibana

---

graffiti/storage/elasticsearch/rollindex.go

When the archive index is rolled, it was not keeping the mappings from
the original archive index.
This produces an incorrect index of values and could reach the max
fields limit if we are using some of the fields that should be
"flattened"

elasticsearch: rolles indices should keep the same mapping

---

.mk/k8s.mk
contrib/charts/skydive-analyzer/Makefile
contrib/charts/skydive-analyzer/fleet.yaml
contrib/charts/skydive-analyzer/values.yaml
contrib/fleet/Makefile
contrib/fleet/skydive.sh

using fleet we deploy the following
- broker (the cluster running the fleet manager)
- east (1st spoke)
- west (2nd spoke)
to test please run:
```
cd contrib/fleet
make tools
make install
make status
```
to connect to any specific cluster via webui localhost:8082 run:
```
make broker
make east
make west
```
and when viewing the broker you see all clusters:

Charts:  use fleet to deploy skydive-analyzer on multi-cluster

---

gremlin/traversal/descendants.go

A new parameter has been added to the Descendants step so nodes linked
with edge types "ownership_shared" are also "descendants" nodes.
This is added so we can have several parents for a single node.

Descendants step parameter to include multiple edge types

---

Dockerfile
Makefile

There is no clear Dockerfile or easy way to build a local docker image.
This patch allows to run 'make docker' and it will use a multi-stage
Dockerfile inspired by the CI Dockerfile for the build.
It allows to use DOCKER_IMAGE and DOCKER_TAG, which are defined on
.mk/dist for docker-image target, which is not great for local
development since the build runs on the host, not in container.

Add Dockerfile and make target

---

analyzer/probes.go
etc/skydive.yml.default
topology/probes/ovn/ovn.go

Up till now, OVN would only work if UNIX sockets were used or TCP without authentication.
This change adds parameters and plumbing for client cert, key
and CA cert file.
That is then passed on to the goovn NewClient.

Add SSL support to OVN

---

.mk/tests.mk
Makefile
analyzer/probes.go
scripts/ci/ovnkube-setup.sh
scripts/ci/run-ovnk8s-tests.sh
scripts/ci/run-tests-utils.sh
tests/k8s/deployment_modern.yaml
tests/k8s_test.go
tests/ovn_test.go
tests/ovnk8s_test.go
tests/tests.go
topology/probes/ovn/ovn.go
topology/probes/ovnk8s/ovnk8s.go

Add a new probe that enriches the topology graph with ovn-kubernetes information.
For now it is a very simple probe that only links pods with their logical switch ports based on their name. Starting with this as the base for more future features.
In deployments where ovn-kubernetes is present (e.g: openshift), this probes connects the information provided by the ovn probe and the kubernetes objects dectected by the k8s probe.
This PR introduces a basic testing infrastructure:
- A new [kind](https://kind.sigs.k8s.io/)-based environment that also installs ovnk8s on top of it (based on [OVN kubernetes KIND setup](https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/kind.md)). The ovnk8s-kind setup is controlled by a script in `scripts/ci/ovnkube-setup.sh`. This script is could …

Add ovn-kubernetes probe

---

go.sum
graffiti/go.mod
graffiti/storage/elasticsearch/client.go

This commmit modify Search method to return an error if any shard has
failed.
If some shards are failing in a ES query, the "Do()" method could return
no error. Those errors will be in res.Shards.Failures

ES detect partial failures

---

graffiti/graph/cachedbackend.go
graffiti/graph/elasticsearch.go
graffiti/graph/graph.go
graffiti/graph/memory.go
graffiti/graph/orientdb.go
graffiti/graph/traversal/traversal.go

Do just one call to get all the edges for the given nodes, instead of
one call for each node.
This new call has been added as a new method to Graph and Backends.
GetNodesEdges, return the list with all edges for a list of nodes.
Batching is used to avoid hitting the max number of clauses set by ES
(is set to the default value of 512).

Improve subgraph performance with persistent backends

---

analyzer/server.go
go.mod
go.sum
graffiti/graph/cachedbackend.go
graffiti/graph/elasticsearch.go
graffiti/graph/graph.go
graffiti/graph/memory.go
graffiti/graph/orientdb.go
graffiti/graph/traversal/traversal.go
gremlin/traversal/neighbors.go
gremlin/traversal/neighbors_test.go
gremlin/traversal/token.go
validator/validator.go

Like Descendants, but using edges in any direction (Descendants only
uses edges from parent to child, Neighbors uses from parent to child and
from child to parent).
The different with the Both step, is Neighbors accumulate nodes seen.
Example (pseudo-syntax):
A -> B -> C
G.V(A).Out().Out() return: C.
But:
G.V(A).Neighbors(2) return: A,B,C
The parameters allowed are the same as in Descendants.
Example:
G.V('foo').Neighbors('RelationType',Within('ownership','foobar'),2)

Neighbors step

---

graffiti/graph/elasticsearch.go
graffiti/graph/elasticsearch_test.go
graffiti/storage/elasticsearch/client.go

The Sync method for the ElasticSearch backend was limited to a maximum
of 20k documents (10k nodes + 10k edges).
This is a clear limiting factor when the skydive database starts to
growth over 10k nodes (or edges).
To avoid increasing that fixed limit, we move the Sync method to use the
scroll api (https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#scroll-search-results).
This API is used to retrieve large numbers of results, using several
requests.
A pattern of one consumer and one producer in different goroutines is
being used to avoid creating a hige slice with all the results.
Testing with 51k nodes in the live index, using 3.3MB of space, it took
around 2" to sync, receiving from ES around 1MB of data (gzipped) in 6
requests to the scroll …

ElasticSearch allow to recover more than 10k documents

---

graffiti/graph/graph.go

UpdateMetadata was always sending a NodeUpdated event, even when the
updated object was an edge.
That was causing a panic in EventHandler.notifyListeners:
interface conversion: interface {} is *graph.Edge, not *graph.Node

graffiti: fix event generated by UpdateMetadata

---

graffiti/graph/traversal/traversal.go
graffiti/graph/traversal/traversal_test.go

When using Subgraph() with nodes (G.V().SubGraph()), now it is possible
to filter which edges we want to return, instead of all connecting the
selected nodes.
For example, if we have two nodes, A and B, and two edges between them,
"e1" and "e1", now we can use this syntaxis to just return the edge
"e1".
G.V().SubGraph("Name", "e1")
The syntaxis inside of SubGraph is the same as in 'Has'.

Graffiti: subgraph edge filtering

---

Dockerfile

Fix this error when running the `Dockefile`

Fix missing curl when running the Dockerfile

---

flow/flow.go

Using github.com/golang/protobuf/protoc-gen-go generates new fields
that cause function `structFieldKeys` to loop forever

Fix generation of Flow fields

---

contrib/openshift/skydive-flow-exporter-template.yaml
contrib/openshift/skydive-template.yaml

Openshift moved the Template resource from api v1 to template.openshift.io/v1 on Openshift V4+. updating the OCP deploying script for the same.
more details: https://access.redhat.com/solutions/7067952

Update OCP Template resource's apiVersion
